<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'জেন্টস-দুই ফিতা',
                'code' => '100',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 4,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 1000.0,
                'price' => 1300.0,
                'qty' => 0.0,
                'alert_quantity' => NULL,
                'daily_sale_objective' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'retailer_202606281245071.jpg',
                'file' => NULL,
                'is_embeded' => 0,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => 0,
                'is_imei' => NULL,
                'featured' => 0,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '<p>Best Shoes For Men</p>',
                'variant_option' => NULL,
                'variant_value' => NULL,
                'is_active' => 1,
                'created_at' => '2026-06-28 12:45:07',
                'updated_at' => '2026-06-28 13:00:11',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'লেডিস-নাগড়া',
                'code' => 'R-2',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 5,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 1000.0,
                'price' => 1500.0,
                'qty' => 11.0,
                'alert_quantity' => NULL,
                'daily_sale_objective' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'retailer_202606281246361.jpg',
                'file' => NULL,
                'is_embeded' => NULL,
                'is_variant' => NULL,
                'is_batch' => NULL,
                'is_diffPrice' => NULL,
                'is_imei' => NULL,
                'featured' => NULL,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '<p>For Women</p>',
                'variant_option' => NULL,
                'variant_value' => NULL,
                'is_active' => 1,
                'created_at' => '2026-06-28 12:46:36',
                'updated_at' => '2026-06-28 13:48:51',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'জেন্টস-দুই ফিতা',
                'code' => 'R-3',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 4,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 1000.0,
                'price' => 1500.0,
                'qty' => 0.0,
                'alert_quantity' => 2.0,
                'daily_sale_objective' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'retailer_202606280103541.jpg',
                'file' => NULL,
                'is_embeded' => NULL,
                'is_variant' => 1,
                'is_batch' => NULL,
                'is_diffPrice' => NULL,
                'is_imei' => NULL,
                'featured' => NULL,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'variant_option' => '["Color","Size"]',
                'variant_value' => '["Black","40,41"]',
                'is_active' => 1,
                'created_at' => '2026-06-28 13:03:54',
                'updated_at' => '2026-06-28 13:21:16',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'জেন্টস-দুই ফিতা',
                'code' => 'R-4',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 4,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 1000.0,
                'price' => 1500.0,
                'qty' => 0.0,
                'alert_quantity' => 2.0,
                'daily_sale_objective' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'retailer_202606280414271.jpg',
                'file' => NULL,
                'is_embeded' => NULL,
                'is_variant' => 1,
                'is_batch' => NULL,
                'is_diffPrice' => NULL,
                'is_imei' => NULL,
                'featured' => NULL,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'variant_option' => '["Color","Size"]',
                'variant_value' => '["Black","39,40,41,42"]',
                'is_active' => 1,
                'created_at' => '2026-06-28 16:14:27',
                'updated_at' => '2026-07-26 14:37:00',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'জেন্টস-দুই ফিতা',
                'code' => 'R-5',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 4,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 10000.0,
                'price' => 20000.0,
                'qty' => 0.0,
                'alert_quantity' => 2.0,
                'daily_sale_objective' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'retailer_202607260216171.jpg',
                'file' => NULL,
                'is_embeded' => NULL,
                'is_variant' => 1,
                'is_batch' => NULL,
                'is_diffPrice' => NULL,
                'is_imei' => NULL,
                'featured' => NULL,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'variant_option' => '["Color","Size"]',
                'variant_value' => '["Black","21,22,23,24,25"]',
                'is_active' => 1,
                'created_at' => '2026-07-26 14:16:17',
                'updated_at' => '2026-07-26 14:16:17',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'লেডিস-নাগড়া',
                'code' => 'R-6',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 5,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 2000.0,
                'price' => 3000.0,
                'qty' => 24.0,
                'alert_quantity' => 2.0,
                'daily_sale_objective' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'retailer_202607260225491.jpg',
                'file' => NULL,
                'is_embeded' => NULL,
                'is_variant' => 1,
                'is_batch' => NULL,
                'is_diffPrice' => NULL,
                'is_imei' => NULL,
                'featured' => NULL,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'variant_option' => '["Color","Size"]',
                'variant_value' => '["Green,Red","21,22,23,24,25"]',
                'is_active' => 1,
                'created_at' => '2026-07-26 14:25:49',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'লেডিস-নাগড়া',
                'code' => 'R-7',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 5,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 1000.0,
                'price' => 2000.0,
                'qty' => 60.0,
                'alert_quantity' => 2.0,
                'daily_sale_objective' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'retailer_202607260235471.jpg',
                'file' => NULL,
                'is_embeded' => NULL,
                'is_variant' => 1,
                'is_batch' => NULL,
                'is_diffPrice' => NULL,
                'is_imei' => NULL,
                'featured' => NULL,
                'product_list' => NULL,
                'variant_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'product_details' => '',
                'variant_option' => '["Color","Size"]',
                'variant_value' => '["Green,Red","22,12,1232,32,321"]',
                'is_active' => 1,
                'created_at' => '2026-07-26 14:35:47',
                'updated_at' => '2026-07-26 17:48:21',
            ),
        ));
        
        
    }
}