<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductReturnsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_returns')->delete();
        
        \DB::table('product_returns')->insert(array (
            0 => 
            array (
                'id' => 1,
                'return_id' => 1,
                'product_id' => 39,
                'product_batch_id' => NULL,
                'variant_id' => 10,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1890.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1890.0,
                'created_at' => '2024-12-27 17:31:28',
                'updated_at' => '2024-12-27 17:31:28',
            ),
            1 => 
            array (
                'id' => 2,
                'return_id' => 2,
                'product_id' => 49,
                'product_batch_id' => NULL,
                'variant_id' => 83,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1341.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1341.0,
                'created_at' => '2024-12-31 13:24:34',
                'updated_at' => '2024-12-31 13:24:34',
            ),
            2 => 
            array (
                'id' => 3,
                'return_id' => 3,
                'product_id' => 36,
                'product_batch_id' => NULL,
                'variant_id' => 75,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1971.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1971.0,
                'created_at' => '2024-12-31 14:59:05',
                'updated_at' => '2024-12-31 14:59:05',
            ),
            3 => 
            array (
                'id' => 4,
                'return_id' => 4,
                'product_id' => 377,
                'product_batch_id' => NULL,
                'variant_id' => 383,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 695.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 695.0,
                'created_at' => '2025-01-02 13:38:46',
                'updated_at' => '2025-01-02 13:38:46',
            ),
            4 => 
            array (
                'id' => 5,
                'return_id' => 5,
                'product_id' => 18,
                'product_batch_id' => NULL,
                'variant_id' => 32,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2190.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2190.0,
                'created_at' => '2025-01-02 17:27:07',
                'updated_at' => '2025-01-02 17:27:07',
            ),
            5 => 
            array (
                'id' => 6,
                'return_id' => 6,
                'product_id' => 48,
                'product_batch_id' => NULL,
                'variant_id' => 78,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1341.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1341.0,
                'created_at' => '2025-01-02 19:57:03',
                'updated_at' => '2025-01-02 19:57:03',
            ),
            6 => 
            array (
                'id' => 7,
                'return_id' => 7,
                'product_id' => 67,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2490.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2490.0,
                'created_at' => '2025-01-04 19:13:48',
                'updated_at' => '2025-01-04 19:13:48',
            ),
            7 => 
            array (
                'id' => 8,
                'return_id' => 8,
                'product_id' => 381,
                'product_batch_id' => NULL,
                'variant_id' => 306,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1790.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1790.0,
                'created_at' => '2025-01-05 17:02:23',
                'updated_at' => '2025-01-05 17:02:23',
            ),
            8 => 
            array (
                'id' => 9,
                'return_id' => 9,
                'product_id' => 379,
                'product_batch_id' => NULL,
                'variant_id' => 388,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2790.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2790.0,
                'created_at' => '2025-01-05 18:36:34',
                'updated_at' => '2025-01-05 18:36:34',
            ),
            9 => 
            array (
                'id' => 10,
                'return_id' => 10,
                'product_id' => 11,
                'product_batch_id' => NULL,
                'variant_id' => 23,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2690.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2690.0,
                'created_at' => '2025-01-09 19:36:13',
                'updated_at' => '2025-01-09 19:36:13',
            ),
            10 => 
            array (
                'id' => 18,
                'return_id' => 17,
                'product_id' => 394,
                'product_batch_id' => NULL,
                'variant_id' => 419,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-01-12 19:13:28',
                'updated_at' => '2025-01-12 19:13:28',
            ),
            11 => 
            array (
                'id' => 19,
                'return_id' => 18,
                'product_id' => 122,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1055.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1055.0,
                'created_at' => '2025-01-15 15:53:16',
                'updated_at' => '2025-01-15 15:53:16',
            ),
            12 => 
            array (
                'id' => 20,
                'return_id' => 19,
                'product_id' => 367,
                'product_batch_id' => NULL,
                'variant_id' => 351,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-01-15 19:08:00',
                'updated_at' => '2025-01-15 19:08:00',
            ),
            13 => 
            array (
                'id' => 21,
                'return_id' => 20,
                'product_id' => 437,
                'product_batch_id' => NULL,
                'variant_id' => 41,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1990.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1990.0,
                'created_at' => '2025-01-16 13:24:09',
                'updated_at' => '2025-01-16 13:24:09',
            ),
            14 => 
            array (
                'id' => 22,
                'return_id' => 21,
                'product_id' => 17,
                'product_batch_id' => NULL,
                'variant_id' => 9,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2890.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2890.0,
                'created_at' => '2025-01-16 20:03:32',
                'updated_at' => '2025-01-16 20:03:32',
            ),
            15 => 
            array (
                'id' => 23,
                'return_id' => 22,
                'product_id' => 360,
                'product_batch_id' => NULL,
                'variant_id' => 354,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1490.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1490.0,
                'created_at' => '2025-01-18 16:18:17',
                'updated_at' => '2025-01-18 16:18:17',
            ),
            16 => 
            array (
                'id' => 24,
                'return_id' => 23,
                'product_id' => 298,
                'product_batch_id' => NULL,
                'variant_id' => 247,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 3395.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3395.0,
                'created_at' => '2025-01-19 19:16:49',
                'updated_at' => '2025-01-19 19:16:49',
            ),
            17 => 
            array (
                'id' => 25,
                'return_id' => 24,
                'product_id' => 84,
                'product_batch_id' => NULL,
                'variant_id' => 161,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1495.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1495.0,
                'created_at' => '2025-01-21 17:37:47',
                'updated_at' => '2025-01-21 17:37:47',
            ),
            18 => 
            array (
                'id' => 26,
                'return_id' => 25,
                'product_id' => 354,
                'product_batch_id' => NULL,
                'variant_id' => 343,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1990.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1990.0,
                'created_at' => '2025-01-21 19:12:00',
                'updated_at' => '2025-01-21 19:12:00',
            ),
            19 => 
            array (
                'id' => 27,
                'return_id' => 26,
                'product_id' => 92,
                'product_batch_id' => NULL,
                'variant_id' => 165,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 855.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 855.0,
                'created_at' => '2025-01-25 18:14:45',
                'updated_at' => '2025-01-25 18:14:45',
            ),
            20 => 
            array (
                'id' => 28,
                'return_id' => 27,
                'product_id' => 316,
                'product_batch_id' => NULL,
                'variant_id' => 18,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1550.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1550.0,
                'created_at' => '2025-01-26 13:04:14',
                'updated_at' => '2025-01-26 13:04:14',
            ),
            21 => 
            array (
                'id' => 29,
                'return_id' => 28,
                'product_id' => 448,
                'product_batch_id' => NULL,
                'variant_id' => 301,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 795.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 795.0,
                'created_at' => '2025-01-26 17:39:00',
                'updated_at' => '2025-01-26 17:39:00',
            ),
            22 => 
            array (
                'id' => 30,
                'return_id' => 29,
                'product_id' => 92,
                'product_batch_id' => NULL,
                'variant_id' => 166,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 950.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 950.0,
                'created_at' => '2025-01-26 18:11:02',
                'updated_at' => '2025-01-26 18:11:02',
            ),
            23 => 
            array (
                'id' => 31,
                'return_id' => 30,
                'product_id' => 117,
                'product_batch_id' => NULL,
                'variant_id' => 53,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1495.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1495.0,
                'created_at' => '2025-01-28 17:16:55',
                'updated_at' => '2025-01-28 17:16:55',
            ),
            24 => 
            array (
                'id' => 32,
                'return_id' => 31,
                'product_id' => 117,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1495.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1495.0,
                'created_at' => '2025-01-30 11:28:50',
                'updated_at' => '2025-01-30 11:28:50',
            ),
            25 => 
            array (
                'id' => 33,
                'return_id' => 32,
                'product_id' => 110,
                'product_batch_id' => NULL,
                'variant_id' => 167,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 895.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 895.0,
                'created_at' => '2025-02-02 12:29:57',
                'updated_at' => '2025-02-02 12:29:57',
            ),
            26 => 
            array (
                'id' => 35,
                'return_id' => 34,
                'product_id' => 109,
                'product_batch_id' => NULL,
                'variant_id' => 59,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1390.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1390.0,
                'created_at' => '2025-02-06 21:55:54',
                'updated_at' => '2025-02-06 21:55:54',
            ),
            27 => 
            array (
                'id' => 36,
                'return_id' => 35,
                'product_id' => 299,
                'product_batch_id' => NULL,
                'variant_id' => 277,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1295.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1295.0,
                'created_at' => '2025-02-09 16:35:16',
                'updated_at' => '2025-02-09 16:35:16',
            ),
            28 => 
            array (
                'id' => 37,
                'return_id' => 36,
                'product_id' => 13,
                'product_batch_id' => NULL,
                'variant_id' => 31,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2690.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2690.0,
                'created_at' => '2025-02-11 13:47:02',
                'updated_at' => '2025-02-11 13:47:02',
            ),
            29 => 
            array (
                'id' => 38,
                'return_id' => 37,
                'product_id' => 311,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2375.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2375.0,
                'created_at' => '2025-02-12 11:25:44',
                'updated_at' => '2025-02-12 11:25:44',
            ),
            30 => 
            array (
                'id' => 39,
                'return_id' => 38,
                'product_id' => 117,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1495.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1495.0,
                'created_at' => '2025-02-16 16:47:03',
                'updated_at' => '2025-02-16 16:47:03',
            ),
            31 => 
            array (
                'id' => 40,
                'return_id' => 39,
                'product_id' => 255,
                'product_batch_id' => NULL,
                'variant_id' => 209,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1995.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1995.0,
                'created_at' => '2025-02-16 18:03:19',
                'updated_at' => '2025-02-16 18:03:19',
            ),
            32 => 
            array (
                'id' => 41,
                'return_id' => 40,
                'product_id' => 123,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1055.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1055.0,
                'created_at' => '2025-02-18 17:02:55',
                'updated_at' => '2025-02-18 17:02:55',
            ),
            33 => 
            array (
                'id' => 42,
                'return_id' => 41,
                'product_id' => 389,
                'product_batch_id' => NULL,
                'variant_id' => 404,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 3090.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3090.0,
                'created_at' => '2025-02-19 12:16:51',
                'updated_at' => '2025-02-19 12:16:51',
            ),
            34 => 
            array (
                'id' => 43,
                'return_id' => 42,
                'product_id' => 523,
                'product_batch_id' => NULL,
                'variant_id' => 520,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 995.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 995.0,
                'created_at' => '2025-02-25 12:17:31',
                'updated_at' => '2025-02-25 12:17:31',
            ),
            35 => 
            array (
                'id' => 44,
                'return_id' => 43,
                'product_id' => 574,
                'product_batch_id' => NULL,
                'variant_id' => 354,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 950.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 950.0,
                'created_at' => '2025-02-25 12:23:32',
                'updated_at' => '2025-02-25 12:23:32',
            ),
            36 => 
            array (
                'id' => 45,
                'return_id' => 44,
                'product_id' => 452,
                'product_batch_id' => NULL,
                'variant_id' => 66,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 795.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 795.0,
                'created_at' => '2025-02-25 14:56:49',
                'updated_at' => '2025-02-25 14:56:49',
            ),
            37 => 
            array (
                'id' => 46,
                'return_id' => 45,
                'product_id' => 797,
                'product_batch_id' => NULL,
                'variant_id' => 153,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1890.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1890.0,
                'created_at' => '2025-02-25 17:16:33',
                'updated_at' => '2025-02-25 17:16:33',
            ),
            38 => 
            array (
                'id' => 47,
                'return_id' => 46,
                'product_id' => 665,
                'product_batch_id' => NULL,
                'variant_id' => 20,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1095.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1095.0,
                'created_at' => '2025-02-25 18:19:31',
                'updated_at' => '2025-02-25 18:19:31',
            ),
            39 => 
            array (
                'id' => 48,
                'return_id' => 47,
                'product_id' => 34,
                'product_batch_id' => NULL,
                'variant_id' => 7,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2490.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2490.0,
                'created_at' => '2025-02-27 19:09:11',
                'updated_at' => '2025-02-27 19:09:11',
            ),
            40 => 
            array (
                'id' => 49,
                'return_id' => 48,
                'product_id' => 143,
                'product_batch_id' => NULL,
                'variant_id' => 199,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 995.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 995.0,
                'created_at' => '2025-03-01 19:22:10',
                'updated_at' => '2025-03-01 19:22:10',
            ),
            41 => 
            array (
                'id' => 50,
                'return_id' => 49,
                'product_id' => 808,
                'product_batch_id' => NULL,
                'variant_id' => 730,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-03-01 23:04:35',
                'updated_at' => '2025-03-01 23:04:35',
            ),
            42 => 
            array (
                'id' => 51,
                'return_id' => 50,
                'product_id' => 750,
                'product_batch_id' => NULL,
                'variant_id' => 221,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 795.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 795.0,
                'created_at' => '2025-03-04 18:08:07',
                'updated_at' => '2025-03-04 18:08:07',
            ),
            43 => 
            array (
                'id' => 52,
                'return_id' => 50,
                'product_id' => 450,
                'product_batch_id' => NULL,
                'variant_id' => 162,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 895.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 895.0,
                'created_at' => '2025-03-04 18:08:08',
                'updated_at' => '2025-03-04 18:08:08',
            ),
            44 => 
            array (
                'id' => 53,
                'return_id' => 51,
                'product_id' => 806,
                'product_batch_id' => NULL,
                'variant_id' => 153,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1690.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1690.0,
                'created_at' => '2025-03-05 03:11:37',
                'updated_at' => '2025-03-05 03:11:37',
            ),
            45 => 
            array (
                'id' => 54,
                'return_id' => 52,
                'product_id' => 332,
                'product_batch_id' => NULL,
                'variant_id' => 20,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1095.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1095.0,
                'created_at' => '2025-03-06 03:53:32',
                'updated_at' => '2025-03-06 03:53:32',
            ),
            46 => 
            array (
                'id' => 55,
                'return_id' => 53,
                'product_id' => 178,
                'product_batch_id' => NULL,
                'variant_id' => 46,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1495.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1495.0,
                'created_at' => '2025-03-06 04:28:44',
                'updated_at' => '2025-03-06 04:28:44',
            ),
            47 => 
            array (
                'id' => 56,
                'return_id' => 54,
                'product_id' => 470,
                'product_batch_id' => NULL,
                'variant_id' => 163,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1595.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1595.0,
                'created_at' => '2025-03-06 17:04:43',
                'updated_at' => '2025-03-06 17:04:43',
            ),
            48 => 
            array (
                'id' => 57,
                'return_id' => 55,
                'product_id' => 237,
                'product_batch_id' => NULL,
                'variant_id' => 209,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 690.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 690.0,
                'created_at' => '2025-03-06 21:49:01',
                'updated_at' => '2025-03-06 21:49:01',
            ),
        ));
        
        
    }
}