<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'জেন্টস-দুই ফিতা',
                'code' => '100',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 4,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 500.0,
                'price' => 600.0,
                'qty' => 3.0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'erp_pos_two_202608220136581.jpg',
                'featured' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'file' => NULL,
                'product_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'is_variant' => NULL,
                'is_diffPrice' => NULL,
                'is_batch' => NULL,
                'variant_list' => NULL,
                'is_imei' => NULL,
                'daily_sale_objective' => NULL,
                'is_embeded' => NULL,
                'variant_option' => NULL,
                'variant_value' => NULL,
                'created_at' => '2026-08-22 13:36:58',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'জেন্টস-দুই ফিতা',
                'code' => 'R-2',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 4,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 500.0,
                'price' => 700.0,
                'qty' => 12.0,
                'alert_quantity' => 1.0,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'erp_pos_two_202608220137391.jpg',
                'featured' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'file' => NULL,
                'product_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'is_variant' => 1,
                'is_diffPrice' => NULL,
                'is_batch' => NULL,
                'variant_list' => NULL,
                'is_imei' => NULL,
                'daily_sale_objective' => NULL,
                'is_embeded' => NULL,
                'variant_option' => '["Color","Size"]',
                'variant_value' => '["Black","10,12,14,16,18,20"]',
                'created_at' => '2026-08-22 13:37:39',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'জেন্টস-দুই ফিতা',
                'code' => 'R-3',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 2,
                'category_id' => 4,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 300.0,
                'price' => 1000.0,
                'qty' => 12.0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'erp_pos_two_202608220138241.jpg',
                'featured' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'file' => NULL,
                'product_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'is_variant' => 1,
                'is_diffPrice' => NULL,
                'is_batch' => NULL,
                'variant_list' => NULL,
                'is_imei' => NULL,
                'daily_sale_objective' => NULL,
                'is_embeded' => NULL,
                'variant_option' => '["Color","Size"]',
                'variant_value' => '["Red","01,02,03,04,05,06"]',
                'created_at' => '2026-08-22 13:38:24',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'লেডিস-নাগড়া',
                'code' => 'R-4',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 3,
                'category_id' => 5,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 200.0,
                'price' => 300.0,
                'qty' => 14.0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'erp_pos_two_202608220139241.jpg',
                'featured' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'file' => NULL,
                'product_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'is_variant' => 1,
                'is_diffPrice' => NULL,
                'is_batch' => NULL,
                'variant_list' => NULL,
                'is_imei' => NULL,
                'daily_sale_objective' => NULL,
                'is_embeded' => NULL,
                'variant_option' => '["Color","Size"]',
                'variant_value' => '["Green","40,41,42,43,44,45,46"]',
                'created_at' => '2026-08-22 13:39:24',
                'updated_at' => '2026-08-22 15:42:15',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'জেন্টস-দুই ফিতা',
                'code' => 'R-5',
                'type' => 'standard',
                'barcode_symbology' => 'C128',
                'brand_id' => 4,
                'category_id' => 4,
                'unit_id' => 1,
                'purchase_unit_id' => 1,
                'sale_unit_id' => 1,
                'cost' => 300.0,
                'price' => 350.0,
                'qty' => 10.0,
                'alert_quantity' => NULL,
                'promotion' => NULL,
                'promotion_price' => NULL,
                'starting_date' => NULL,
                'last_date' => NULL,
                'tax_id' => NULL,
                'tax_method' => 1,
                'image' => 'erp_pos_two_202608220140061.jpg',
                'featured' => NULL,
                'product_details' => '',
                'is_active' => 1,
                'file' => NULL,
                'product_list' => NULL,
                'qty_list' => NULL,
                'price_list' => NULL,
                'is_variant' => 1,
                'is_diffPrice' => NULL,
                'is_batch' => NULL,
                'variant_list' => NULL,
                'is_imei' => NULL,
                'daily_sale_objective' => NULL,
                'is_embeded' => NULL,
                'variant_option' => '["Color","Size"]',
                'variant_value' => '["Black","20,21,22,23,24"]',
                'created_at' => '2026-08-22 13:40:06',
                'updated_at' => '2026-08-22 15:42:16',
            ),
        ));
        
        
    }
}