<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductTransferTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_transfer')->delete();
        
        \DB::table('product_transfer')->insert(array (
            0 => 
            array (
                'id' => 1,
                'transfer_id' => 1,
                'product_id' => 482,
                'product_batch_id' => NULL,
                'variant_id' => 129,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 558.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 558.0,
                'created_at' => '2026-06-19 15:42:14',
                'updated_at' => '2026-06-19 15:42:14',
            ),
            1 => 
            array (
                'id' => 2,
                'transfer_id' => 1,
                'product_id' => 482,
                'product_batch_id' => NULL,
                'variant_id' => 136,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 558.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 558.0,
                'created_at' => '2026-06-19 15:42:14',
                'updated_at' => '2026-06-19 15:42:14',
            ),
            2 => 
            array (
                'id' => 3,
                'transfer_id' => 2,
                'product_id' => 863,
                'product_batch_id' => NULL,
                'variant_id' => 23,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2100.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2100.0,
                'created_at' => '2026-06-20 15:27:07',
                'updated_at' => '2026-06-20 15:27:07',
            ),
            3 => 
            array (
                'id' => 4,
                'transfer_id' => 2,
                'product_id' => 863,
                'product_batch_id' => NULL,
                'variant_id' => 25,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2100.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2100.0,
                'created_at' => '2026-06-20 15:27:07',
                'updated_at' => '2026-06-20 15:27:07',
            ),
            4 => 
            array (
                'id' => 5,
                'transfer_id' => 2,
                'product_id' => 863,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2100.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2100.0,
                'created_at' => '2026-06-20 15:27:07',
                'updated_at' => '2026-06-20 15:27:07',
            ),
            5 => 
            array (
                'id' => 6,
                'transfer_id' => 2,
                'product_id' => 863,
                'product_batch_id' => NULL,
                'variant_id' => 395,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2100.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2100.0,
                'created_at' => '2026-06-20 15:27:07',
                'updated_at' => '2026-06-20 15:27:07',
            ),
            6 => 
            array (
                'id' => 7,
                'transfer_id' => 3,
                'product_id' => 1058,
                'product_batch_id' => NULL,
                'variant_id' => 29,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 462.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 462.0,
                'created_at' => '2026-06-20 15:30:33',
                'updated_at' => '2026-06-20 15:30:33',
            ),
            7 => 
            array (
                'id' => 8,
                'transfer_id' => 3,
                'product_id' => 1058,
                'product_batch_id' => NULL,
                'variant_id' => 46,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 477.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 477.0,
                'created_at' => '2026-06-20 15:30:34',
                'updated_at' => '2026-06-20 15:30:34',
            ),
            8 => 
            array (
                'id' => 9,
                'transfer_id' => 4,
                'product_id' => 1042,
                'product_batch_id' => NULL,
                'variant_id' => 60,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 847.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 847.0,
                'created_at' => '2026-06-20 18:30:53',
                'updated_at' => '2026-06-20 18:30:53',
            ),
            9 => 
            array (
                'id' => 10,
                'transfer_id' => 4,
                'product_id' => 1042,
                'product_batch_id' => NULL,
                'variant_id' => 61,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 847.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 847.0,
                'created_at' => '2026-06-20 18:30:53',
                'updated_at' => '2026-06-20 18:30:53',
            ),
            10 => 
            array (
                'id' => 11,
                'transfer_id' => 4,
                'product_id' => 1042,
                'product_batch_id' => NULL,
                'variant_id' => 62,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 847.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 847.0,
                'created_at' => '2026-06-20 18:30:53',
                'updated_at' => '2026-06-20 18:30:53',
            ),
            11 => 
            array (
                'id' => 12,
                'transfer_id' => 4,
                'product_id' => 1042,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 847.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 847.0,
                'created_at' => '2026-06-20 18:30:53',
                'updated_at' => '2026-06-20 18:30:53',
            ),
            12 => 
            array (
                'id' => 13,
                'transfer_id' => 4,
                'product_id' => 1042,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 847.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 847.0,
                'created_at' => '2026-06-20 18:30:53',
                'updated_at' => '2026-06-20 18:30:53',
            ),
            13 => 
            array (
                'id' => 14,
                'transfer_id' => 5,
                'product_id' => 1053,
                'product_batch_id' => NULL,
                'variant_id' => 126,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 780.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 780.0,
                'created_at' => '2026-06-21 19:14:48',
                'updated_at' => '2026-06-21 19:14:48',
            ),
            14 => 
            array (
                'id' => 15,
                'transfer_id' => 6,
                'product_id' => 1064,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 943.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 943.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            15 => 
            array (
                'id' => 16,
                'transfer_id' => 6,
                'product_id' => 1063,
                'product_batch_id' => NULL,
                'variant_id' => 22,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 736.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 736.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            16 => 
            array (
                'id' => 17,
                'transfer_id' => 6,
                'product_id' => 1059,
                'product_batch_id' => NULL,
                'variant_id' => 427,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 854.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 854.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            17 => 
            array (
                'id' => 18,
                'transfer_id' => 6,
                'product_id' => 1056,
                'product_batch_id' => NULL,
                'variant_id' => 54,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 810.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 810.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            18 => 
            array (
                'id' => 19,
                'transfer_id' => 6,
                'product_id' => 1052,
                'product_batch_id' => NULL,
                'variant_id' => 64,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 366.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 366.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            19 => 
            array (
                'id' => 20,
                'transfer_id' => 6,
                'product_id' => 1044,
                'product_batch_id' => NULL,
                'variant_id' => 63,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 854.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 854.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            20 => 
            array (
                'id' => 21,
                'transfer_id' => 6,
                'product_id' => 1041,
                'product_batch_id' => NULL,
                'variant_id' => 8,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1476.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1476.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            21 => 
            array (
                'id' => 22,
                'transfer_id' => 6,
                'product_id' => 1061,
                'product_batch_id' => NULL,
                'variant_id' => 80,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 928.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 928.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            22 => 
            array (
                'id' => 23,
                'transfer_id' => 6,
                'product_id' => 1061,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 928.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 928.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            23 => 
            array (
                'id' => 24,
                'transfer_id' => 6,
                'product_id' => 1057,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 773.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 773.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            24 => 
            array (
                'id' => 25,
                'transfer_id' => 6,
                'product_id' => 1057,
                'product_batch_id' => NULL,
                'variant_id' => 99,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 781.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 781.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            25 => 
            array (
                'id' => 26,
                'transfer_id' => 6,
                'product_id' => 1054,
                'product_batch_id' => NULL,
                'variant_id' => 81,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 925.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 925.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            26 => 
            array (
                'id' => 27,
                'transfer_id' => 6,
                'product_id' => 1054,
                'product_batch_id' => NULL,
                'variant_id' => 343,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 925.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 925.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            27 => 
            array (
                'id' => 28,
                'transfer_id' => 6,
                'product_id' => 1050,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 588.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 588.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            28 => 
            array (
                'id' => 29,
                'transfer_id' => 6,
                'product_id' => 1050,
                'product_batch_id' => NULL,
                'variant_id' => 15,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 588.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 588.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            29 => 
            array (
                'id' => 30,
                'transfer_id' => 6,
                'product_id' => 1049,
                'product_batch_id' => NULL,
                'variant_id' => 136,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 440.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 440.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            30 => 
            array (
                'id' => 31,
                'transfer_id' => 6,
                'product_id' => 1049,
                'product_batch_id' => NULL,
                'variant_id' => 125,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 514.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 514.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            31 => 
            array (
                'id' => 32,
                'transfer_id' => 6,
                'product_id' => 1045,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 629.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 629.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            32 => 
            array (
                'id' => 33,
                'transfer_id' => 6,
                'product_id' => 1045,
                'product_batch_id' => NULL,
                'variant_id' => 24,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 629.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 629.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            33 => 
            array (
                'id' => 34,
                'transfer_id' => 6,
                'product_id' => 1051,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1028.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1028.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            34 => 
            array (
                'id' => 35,
                'transfer_id' => 6,
                'product_id' => 1051,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1028.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1028.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            35 => 
            array (
                'id' => 36,
                'transfer_id' => 6,
                'product_id' => 1051,
                'product_batch_id' => NULL,
                'variant_id' => 71,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1028.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1028.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            36 => 
            array (
                'id' => 37,
                'transfer_id' => 6,
                'product_id' => 1043,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 869.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 869.0,
                'created_at' => '2026-06-22 01:17:32',
                'updated_at' => '2026-06-22 01:17:32',
            ),
            37 => 
            array (
                'id' => 38,
                'transfer_id' => 6,
                'product_id' => 1043,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 869.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 869.0,
                'created_at' => '2026-06-22 01:17:33',
                'updated_at' => '2026-06-22 01:17:33',
            ),
            38 => 
            array (
                'id' => 39,
                'transfer_id' => 6,
                'product_id' => 1043,
                'product_batch_id' => NULL,
                'variant_id' => 18,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 869.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 869.0,
                'created_at' => '2026-06-22 01:17:33',
                'updated_at' => '2026-06-22 01:17:33',
            ),
            39 => 
            array (
                'id' => 40,
                'transfer_id' => 6,
                'product_id' => 1043,
                'product_batch_id' => NULL,
                'variant_id' => 60,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 869.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 869.0,
                'created_at' => '2026-06-22 01:17:33',
                'updated_at' => '2026-06-22 01:17:33',
            ),
            40 => 
            array (
                'id' => 41,
                'transfer_id' => 6,
                'product_id' => 1043,
                'product_batch_id' => NULL,
                'variant_id' => 62,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 869.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 869.0,
                'created_at' => '2026-06-22 01:17:33',
                'updated_at' => '2026-06-22 01:17:33',
            ),
            41 => 
            array (
                'id' => 42,
                'transfer_id' => 7,
                'product_id' => 863,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2100.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2100.0,
                'created_at' => '2026-06-22 12:29:35',
                'updated_at' => '2026-06-22 12:29:35',
            ),
            42 => 
            array (
                'id' => 43,
                'transfer_id' => 7,
                'product_id' => 1070,
                'product_batch_id' => NULL,
                'variant_id' => 386,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1350.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1350.0,
                'created_at' => '2026-06-22 12:29:35',
                'updated_at' => '2026-06-22 12:29:35',
            ),
            43 => 
            array (
                'id' => 44,
                'transfer_id' => 7,
                'product_id' => 1070,
                'product_batch_id' => NULL,
                'variant_id' => 22,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1350.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1350.0,
                'created_at' => '2026-06-22 12:29:35',
                'updated_at' => '2026-06-22 12:29:35',
            ),
            44 => 
            array (
                'id' => 45,
                'transfer_id' => 7,
                'product_id' => 1070,
                'product_batch_id' => NULL,
                'variant_id' => 23,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1350.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1350.0,
                'created_at' => '2026-06-22 12:29:35',
                'updated_at' => '2026-06-22 12:29:35',
            ),
            45 => 
            array (
                'id' => 46,
                'transfer_id' => 7,
                'product_id' => 1070,
                'product_batch_id' => NULL,
                'variant_id' => 102,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1350.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1350.0,
                'created_at' => '2026-06-22 12:29:35',
                'updated_at' => '2026-06-22 12:29:35',
            ),
            46 => 
            array (
                'id' => 47,
                'transfer_id' => 7,
                'product_id' => 1070,
                'product_batch_id' => NULL,
                'variant_id' => 401,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1350.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1350.0,
                'created_at' => '2026-06-22 12:29:35',
                'updated_at' => '2026-06-22 12:29:35',
            ),
            47 => 
            array (
                'id' => 48,
                'transfer_id' => 7,
                'product_id' => 1068,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1300.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1300.0,
                'created_at' => '2026-06-22 12:29:35',
                'updated_at' => '2026-06-22 12:29:35',
            ),
            48 => 
            array (
                'id' => 49,
                'transfer_id' => 7,
                'product_id' => 1068,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1300.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1300.0,
                'created_at' => '2026-06-22 12:29:35',
                'updated_at' => '2026-06-22 12:29:35',
            ),
            49 => 
            array (
                'id' => 50,
                'transfer_id' => 7,
                'product_id' => 1068,
                'product_batch_id' => NULL,
                'variant_id' => 8,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1350.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1350.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            50 => 
            array (
                'id' => 51,
                'transfer_id' => 7,
                'product_id' => 1068,
                'product_batch_id' => NULL,
                'variant_id' => 11,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1350.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1350.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            51 => 
            array (
                'id' => 52,
                'transfer_id' => 7,
                'product_id' => 1073,
                'product_batch_id' => NULL,
                'variant_id' => 254,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 600.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 600.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            52 => 
            array (
                'id' => 53,
                'transfer_id' => 7,
                'product_id' => 1073,
                'product_batch_id' => NULL,
                'variant_id' => 260,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 600.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 600.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            53 => 
            array (
                'id' => 54,
                'transfer_id' => 7,
                'product_id' => 1073,
                'product_batch_id' => NULL,
                'variant_id' => 256,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 600.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 600.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            54 => 
            array (
                'id' => 55,
                'transfer_id' => 7,
                'product_id' => 1072,
                'product_batch_id' => NULL,
                'variant_id' => 374,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 900.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 900.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            55 => 
            array (
                'id' => 56,
                'transfer_id' => 7,
                'product_id' => 1072,
                'product_batch_id' => NULL,
                'variant_id' => 371,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 900.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 900.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            56 => 
            array (
                'id' => 57,
                'transfer_id' => 7,
                'product_id' => 1075,
                'product_batch_id' => NULL,
                'variant_id' => 259,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 900.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 900.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            57 => 
            array (
                'id' => 58,
                'transfer_id' => 7,
                'product_id' => 1075,
                'product_batch_id' => NULL,
                'variant_id' => 250,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 900.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 900.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            58 => 
            array (
                'id' => 59,
                'transfer_id' => 7,
                'product_id' => 890,
                'product_batch_id' => NULL,
                'variant_id' => 255,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 670.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 670.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            59 => 
            array (
                'id' => 60,
                'transfer_id' => 7,
                'product_id' => 1067,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1050.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1050.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            60 => 
            array (
                'id' => 61,
                'transfer_id' => 7,
                'product_id' => 1071,
                'product_batch_id' => NULL,
                'variant_id' => 206,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            61 => 
            array (
                'id' => 62,
                'transfer_id' => 7,
                'product_id' => 1074,
                'product_batch_id' => NULL,
                'variant_id' => 254,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 700.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 700.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            62 => 
            array (
                'id' => 63,
                'transfer_id' => 7,
                'product_id' => 1076,
                'product_batch_id' => NULL,
                'variant_id' => 254,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
            63 => 
            array (
                'id' => 64,
                'transfer_id' => 7,
                'product_id' => 1077,
                'product_batch_id' => NULL,
                'variant_id' => 228,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 470.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 470.0,
                'created_at' => '2026-06-22 12:29:36',
                'updated_at' => '2026-06-22 12:29:36',
            ),
        ));
        
        
    }
}