<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductPurchasesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_purchases')->delete();
        
        \DB::table('product_purchases')->insert(array (
            0 => 
            array (
                'id' => 1,
                'purchase_id' => 1,
                'product_id' => 1,
                'product_batch_id' => NULL,
                'variant_id' => NULL,
                'imei_number' => NULL,
                'qty' => 6.0,
                'recieved' => 6.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 1300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 6000.0,
                'created_at' => '2026-06-28 13:00:11',
                'updated_at' => '2026-06-28 13:00:11',
            ),
            1 => 
            array (
                'id' => 2,
                'purchase_id' => 2,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'variant_id' => 2,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 1500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-06-28 13:08:57',
                'updated_at' => '2026-06-28 13:08:57',
            ),
            2 => 
            array (
                'id' => 3,
                'purchase_id' => 2,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'variant_id' => 1,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 1500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-06-28 13:08:57',
                'updated_at' => '2026-06-28 13:08:57',
            ),
            3 => 
            array (
                'id' => 4,
                'purchase_id' => 3,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'variant_id' => NULL,
                'imei_number' => NULL,
                'qty' => 6.0,
                'recieved' => 6.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 1500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 6000.0,
                'created_at' => '2026-06-28 13:17:33',
                'updated_at' => '2026-06-28 13:17:33',
            ),
            4 => 
            array (
                'id' => 5,
                'purchase_id' => 4,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'variant_id' => 4,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 1500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:37:00',
                'updated_at' => '2026-07-26 14:37:00',
            ),
            5 => 
            array (
                'id' => 6,
                'purchase_id' => 4,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'variant_id' => 2,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 1500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:37:00',
                'updated_at' => '2026-07-26 14:37:00',
            ),
            6 => 
            array (
                'id' => 7,
                'purchase_id' => 4,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'variant_id' => 1,
                'imei_number' => NULL,
                'qty' => 2.0,
                'recieved' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 1500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:37:00',
                'updated_at' => '2026-07-26 14:37:00',
            ),
            7 => 
            array (
                'id' => 8,
                'purchase_id' => 4,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'variant_id' => 3,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 1500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:37:00',
                'updated_at' => '2026-07-26 14:37:00',
            ),
            8 => 
            array (
                'id' => 9,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 19,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            9 => 
            array (
                'id' => 10,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 18,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            10 => 
            array (
                'id' => 11,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            11 => 
            array (
                'id' => 12,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 2.0,
                'recieved' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 4000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            12 => 
            array (
                'id' => 13,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 15,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            13 => 
            array (
                'id' => 14,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 14,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            14 => 
            array (
                'id' => 15,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 13,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            15 => 
            array (
                'id' => 16,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 12,
                'imei_number' => NULL,
                'qty' => 2.0,
                'recieved' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 4000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            16 => 
            array (
                'id' => 17,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 11,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            17 => 
            array (
                'id' => 18,
                'purchase_id' => 5,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'variant_id' => 10,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2000.0,
                'selling_price' => 3000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 14:42:35',
            ),
            18 => 
            array (
                'id' => 19,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 27,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            19 => 
            array (
                'id' => 20,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            20 => 
            array (
                'id' => 21,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 25,
                'imei_number' => NULL,
                'qty' => 2.0,
                'recieved' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            21 => 
            array (
                'id' => 22,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 24,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            22 => 
            array (
                'id' => 23,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            23 => 
            array (
                'id' => 24,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 23,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            24 => 
            array (
                'id' => 25,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 22,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            25 => 
            array (
                'id' => 26,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 21,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            26 => 
            array (
                'id' => 27,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 20,
                'imei_number' => NULL,
                'qty' => 3.0,
                'recieved' => 3.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            27 => 
            array (
                'id' => 28,
                'purchase_id' => 6,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'variant_id' => 11,
                'imei_number' => NULL,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1000.0,
                'selling_price' => 2000.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
        ));
        
        
    }
}