<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductReturnsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_returns')->delete();
        
        \DB::table('product_returns')->insert(array (
            0 => 
            array (
                'id' => 1,
                'return_id' => 1,
                'product_id' => 39,
                'product_batch_id' => NULL,
                'variant_id' => 10,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1890.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1890.0,
                'created_at' => '2024-12-27 17:31:28',
                'updated_at' => '2024-12-27 17:31:28',
            ),
            1 => 
            array (
                'id' => 2,
                'return_id' => 2,
                'product_id' => 49,
                'product_batch_id' => NULL,
                'variant_id' => 83,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1341.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1341.0,
                'created_at' => '2024-12-31 13:24:34',
                'updated_at' => '2024-12-31 13:24:34',
            ),
            2 => 
            array (
                'id' => 3,
                'return_id' => 3,
                'product_id' => 36,
                'product_batch_id' => NULL,
                'variant_id' => 75,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1971.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1971.0,
                'created_at' => '2024-12-31 14:59:05',
                'updated_at' => '2024-12-31 14:59:05',
            ),
            3 => 
            array (
                'id' => 4,
                'return_id' => 4,
                'product_id' => 377,
                'product_batch_id' => NULL,
                'variant_id' => 383,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 695.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 695.0,
                'created_at' => '2025-01-02 13:38:46',
                'updated_at' => '2025-01-02 13:38:46',
            ),
            4 => 
            array (
                'id' => 5,
                'return_id' => 5,
                'product_id' => 18,
                'product_batch_id' => NULL,
                'variant_id' => 32,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2190.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2190.0,
                'created_at' => '2025-01-02 17:27:07',
                'updated_at' => '2025-01-02 17:27:07',
            ),
            5 => 
            array (
                'id' => 6,
                'return_id' => 6,
                'product_id' => 48,
                'product_batch_id' => NULL,
                'variant_id' => 78,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1341.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1341.0,
                'created_at' => '2025-01-02 19:57:03',
                'updated_at' => '2025-01-02 19:57:03',
            ),
            6 => 
            array (
                'id' => 7,
                'return_id' => 7,
                'product_id' => 67,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2490.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2490.0,
                'created_at' => '2025-01-04 19:13:48',
                'updated_at' => '2025-01-04 19:13:48',
            ),
            7 => 
            array (
                'id' => 8,
                'return_id' => 8,
                'product_id' => 381,
                'product_batch_id' => NULL,
                'variant_id' => 306,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1790.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1790.0,
                'created_at' => '2025-01-05 17:02:23',
                'updated_at' => '2025-01-05 17:02:23',
            ),
            8 => 
            array (
                'id' => 9,
                'return_id' => 9,
                'product_id' => 379,
                'product_batch_id' => NULL,
                'variant_id' => 388,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2790.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2790.0,
                'created_at' => '2025-01-05 18:36:34',
                'updated_at' => '2025-01-05 18:36:34',
            ),
            9 => 
            array (
                'id' => 10,
                'return_id' => 10,
                'product_id' => 11,
                'product_batch_id' => NULL,
                'variant_id' => 23,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2690.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2690.0,
                'created_at' => '2025-01-09 19:36:13',
                'updated_at' => '2025-01-09 19:36:13',
            ),
            10 => 
            array (
                'id' => 18,
                'return_id' => 17,
                'product_id' => 394,
                'product_batch_id' => NULL,
                'variant_id' => 419,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-01-12 19:13:28',
                'updated_at' => '2025-01-12 19:13:28',
            ),
            11 => 
            array (
                'id' => 19,
                'return_id' => 18,
                'product_id' => 122,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1055.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1055.0,
                'created_at' => '2025-01-15 15:53:16',
                'updated_at' => '2025-01-15 15:53:16',
            ),
            12 => 
            array (
                'id' => 20,
                'return_id' => 19,
                'product_id' => 367,
                'product_batch_id' => NULL,
                'variant_id' => 351,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-01-15 19:08:00',
                'updated_at' => '2025-01-15 19:08:00',
            ),
            13 => 
            array (
                'id' => 21,
                'return_id' => 20,
                'product_id' => 437,
                'product_batch_id' => NULL,
                'variant_id' => 41,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1990.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1990.0,
                'created_at' => '2025-01-16 13:24:09',
                'updated_at' => '2025-01-16 13:24:09',
            ),
            14 => 
            array (
                'id' => 22,
                'return_id' => 21,
                'product_id' => 17,
                'product_batch_id' => NULL,
                'variant_id' => 9,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 2890.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2890.0,
                'created_at' => '2025-01-16 20:03:32',
                'updated_at' => '2025-01-16 20:03:32',
            ),
            15 => 
            array (
                'id' => 23,
                'return_id' => 22,
                'product_id' => 360,
                'product_batch_id' => NULL,
                'variant_id' => 354,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 1490.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1490.0,
                'created_at' => '2025-01-18 16:18:17',
                'updated_at' => '2025-01-18 16:18:17',
            ),
            16 => 
            array (
                'id' => 24,
                'return_id' => 23,
                'product_id' => 298,
                'product_batch_id' => NULL,
                'variant_id' => 247,
                'imei_number' => NULL,
                'qty' => 1.0,
                'sale_unit_id' => 1,
                'net_unit_price' => 3395.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3395.0,
                'created_at' => '2025-01-19 19:16:49',
                'updated_at' => '2025-01-19 19:16:49',
            ),
        ));
        
        
    }
}