<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductWarehouseTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_warehouse')->delete();
        
        $records = array (
            0 => 
            array (
                'id' => 1,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 8,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '5-1-8-0',
            ),
            1 => 
            array (
                'id' => 2,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 7,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '5-1-7-0',
            ),
            2 => 
            array (
                'id' => 3,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 6,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '5-1-6-0',
            ),
            3 => 
            array (
                'id' => 4,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 5,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '5-1-5-0',
            ),
            4 => 
            array (
                'id' => 5,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 33,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '5-1-33-0',
            ),
            5 => 
            array (
                'id' => 6,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 46,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '4-1-46-0',
            ),
            6 => 
            array (
                'id' => 7,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 45,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '4-1-45-0',
            ),
            7 => 
            array (
                'id' => 8,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 44,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '4-1-44-0',
            ),
            8 => 
            array (
                'id' => 9,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 43,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '4-1-43-0',
            ),
            9 => 
            array (
                'id' => 10,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 42,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '4-1-42-0',
            ),
            10 => 
            array (
                'id' => 11,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 41,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '4-1-41-0',
            ),
            11 => 
            array (
                'id' => 12,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 40,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '4-1-40-0',
            ),
            12 => 
            array (
                'id' => 13,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 39,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '3-1-39-0',
            ),
            13 => 
            array (
                'id' => 14,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 38,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '3-1-38-0',
            ),
            14 => 
            array (
                'id' => 15,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 37,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '3-1-37-0',
            ),
            15 => 
            array (
                'id' => 16,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 36,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '3-1-36-0',
            ),
            16 => 
            array (
                'id' => 17,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 35,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '3-1-35-0',
            ),
            17 => 
            array (
                'id' => 18,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 34,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '3-1-34-0',
            ),
            18 => 
            array (
                'id' => 19,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 33,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '2-1-33-0',
            ),
            19 => 
            array (
                'id' => 20,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 32,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '2-1-32-0',
            ),
            20 => 
            array (
                'id' => 21,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 31,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '2-1-31-0',
            ),
            21 => 
            array (
                'id' => 22,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 30,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '2-1-30-0',
            ),
            22 => 
            array (
                'id' => 23,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 29,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '2-1-29-0',
            ),
            23 => 
            array (
                'id' => 24,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 28,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '2-1-28-0',
            ),
            24 => 
            array (
                'id' => 25,
                'product_id' => 1,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => NULL,
                'imei_number' => NULL,
                'qty' => 2.0,
                'price' => 600.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
                'unique_key' => '1-1-0-0',
            ),
            25 => 
            array (
                'id' => 26,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 46,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
                'unique_key' => '4-2-46-0',
            ),
            26 => 
            array (
                'id' => 27,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 45,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
                'unique_key' => '4-2-45-0',
            ),
            27 => 
            array (
                'id' => 28,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 44,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
                'unique_key' => '4-2-44-0',
            ),
            28 => 
            array (
                'id' => 29,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 43,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
                'unique_key' => '4-2-43-0',
            ),
            29 => 
            array (
                'id' => 30,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 42,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
                'unique_key' => '4-2-42-0',
            ),
            30 => 
            array (
                'id' => 31,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 41,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
                'unique_key' => '4-2-41-0',
            ),
            31 => 
            array (
                'id' => 32,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 40,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
                'unique_key' => '4-2-40-0',
            ),
            32 => 
            array (
                'id' => 33,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 8,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
                'unique_key' => '5-2-8-0',
            ),
            33 => 
            array (
                'id' => 34,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 7,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '5-2-7-0',
            ),
            34 => 
            array (
                'id' => 35,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 6,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '5-2-6-0',
            ),
            35 => 
            array (
                'id' => 36,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 5,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '5-2-5-0',
            ),
            36 => 
            array (
                'id' => 37,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 33,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 350.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '5-2-33-0',
            ),
            37 => 
            array (
                'id' => 38,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 39,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '3-2-39-0',
            ),
            38 => 
            array (
                'id' => 39,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 38,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '3-2-38-0',
            ),
            39 => 
            array (
                'id' => 40,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 37,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '3-2-37-0',
            ),
            40 => 
            array (
                'id' => 41,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 36,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '3-2-36-0',
            ),
            41 => 
            array (
                'id' => 42,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 35,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '3-2-35-0',
            ),
            42 => 
            array (
                'id' => 43,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 34,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 1000.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '3-2-34-0',
            ),
            43 => 
            array (
                'id' => 44,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 33,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '2-2-33-0',
            ),
            44 => 
            array (
                'id' => 45,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 32,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '2-2-32-0',
            ),
            45 => 
            array (
                'id' => 46,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 31,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '2-2-31-0',
            ),
            46 => 
            array (
                'id' => 47,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 30,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '2-2-30-0',
            ),
            47 => 
            array (
                'id' => 48,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 29,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '2-2-29-0',
            ),
            48 => 
            array (
                'id' => 49,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 28,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 700.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '2-2-28-0',
            ),
            49 => 
            array (
                'id' => 50,
                'product_id' => 1,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => NULL,
                'imei_number' => NULL,
                'qty' => 1.0,
                'price' => 600.0,
                'created_at' => '2026-08-22 15:42:16',
                'updated_at' => '2026-08-22 15:42:16',
                'unique_key' => '1-2-0-0',
            ),
        );
        
        $cleanRecords = array_map(function($row) {
            unset($row['unique_key']);
            return $row;
        }, $records);

        \DB::table('product_warehouse')->insert($cleanRecords);
    }
}