<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductWarehouseTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_warehouse')->delete();
        
        \DB::table('product_warehouse')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_id' => 1,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => NULL,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 1300.0,
                'created_at' => '2026-06-28 13:00:11',
                'updated_at' => '2026-06-28 13:00:11',
            ),
            1 => 
            array (
                'id' => 2,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 2,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 1500.0,
                'created_at' => '2026-06-28 13:08:57',
                'updated_at' => '2026-06-28 13:21:16',
            ),
            2 => 
            array (
                'id' => 3,
                'product_id' => 3,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 1,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 1500.0,
                'created_at' => '2026-06-28 13:08:57',
                'updated_at' => '2026-06-28 13:21:16',
            ),
            3 => 
            array (
                'id' => 4,
                'product_id' => 2,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => NULL,
                'imei_number' => NULL,
                'qty' => 11.0,
                'price' => 1500.0,
                'created_at' => '2026-06-28 13:17:33',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            4 => 
            array (
                'id' => 5,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 4,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 1500.0,
                'created_at' => '2026-07-26 14:37:00',
                'updated_at' => '2026-07-26 14:37:00',
            ),
            5 => 
            array (
                'id' => 6,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 2,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 1500.0,
                'created_at' => '2026-07-26 14:37:00',
                'updated_at' => '2026-07-26 14:37:00',
            ),
            6 => 
            array (
                'id' => 7,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 1,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 1500.0,
                'created_at' => '2026-07-26 14:37:00',
                'updated_at' => '2026-07-26 14:37:00',
            ),
            7 => 
            array (
                'id' => 8,
                'product_id' => 4,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 3,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 1500.0,
                'created_at' => '2026-07-26 14:37:00',
                'updated_at' => '2026-07-26 14:37:00',
            ),
            8 => 
            array (
                'id' => 9,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 19,
                'imei_number' => NULL,
                'qty' => 2.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            9 => 
            array (
                'id' => 10,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 18,
                'imei_number' => NULL,
                'qty' => 2.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            10 => 
            array (
                'id' => 11,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 2.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            11 => 
            array (
                'id' => 12,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 4.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            12 => 
            array (
                'id' => 13,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 15,
                'imei_number' => NULL,
                'qty' => 2.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            13 => 
            array (
                'id' => 14,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 14,
                'imei_number' => NULL,
                'qty' => 2.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            14 => 
            array (
                'id' => 15,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 13,
                'imei_number' => NULL,
                'qty' => 2.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            15 => 
            array (
                'id' => 16,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 12,
                'imei_number' => NULL,
                'qty' => 4.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:47',
            ),
            16 => 
            array (
                'id' => 17,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 11,
                'imei_number' => NULL,
                'qty' => 2.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:47',
            ),
            17 => 
            array (
                'id' => 18,
                'product_id' => 6,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 10,
                'imei_number' => NULL,
                'qty' => 2.0,
                'price' => 3000.0,
                'created_at' => '2026-07-26 14:42:35',
                'updated_at' => '2026-07-26 19:24:47',
            ),
            18 => 
            array (
                'id' => 19,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 27,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            19 => 
            array (
                'id' => 20,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            20 => 
            array (
                'id' => 21,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 25,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            21 => 
            array (
                'id' => 22,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 24,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            22 => 
            array (
                'id' => 23,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 17:48:21',
            ),
            23 => 
            array (
                'id' => 24,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 23,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            24 => 
            array (
                'id' => 25,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 22,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            25 => 
            array (
                'id' => 26,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 21,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            26 => 
            array (
                'id' => 27,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 20,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            27 => 
            array (
                'id' => 28,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 11,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 14:43:01',
                'updated_at' => '2026-07-26 14:43:01',
            ),
            28 => 
            array (
                'id' => 29,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => 2000.0,
                'created_at' => '2026-07-26 17:48:21',
                'updated_at' => '2026-07-26 17:48:21',
            ),
            29 => 
            array (
                'id' => 30,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 27,
                'imei_number' => NULL,
                'qty' => 5.0,
                'price' => NULL,
                'created_at' => '2026-07-26 17:51:30',
                'updated_at' => '2026-07-26 17:51:30',
            ),
            30 => 
            array (
                'id' => 31,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 5.0,
                'price' => NULL,
                'created_at' => '2026-07-26 17:51:30',
                'updated_at' => '2026-07-26 17:51:30',
            ),
            31 => 
            array (
                'id' => 32,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 25,
                'imei_number' => NULL,
                'qty' => 10.0,
                'price' => NULL,
                'created_at' => '2026-07-26 17:51:30',
                'updated_at' => '2026-07-26 17:51:30',
            ),
            32 => 
            array (
                'id' => 33,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 24,
                'imei_number' => NULL,
                'qty' => 5.0,
                'price' => NULL,
                'created_at' => '2026-07-26 17:51:30',
                'updated_at' => '2026-07-26 17:51:30',
            ),
            33 => 
            array (
                'id' => 34,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 23,
                'imei_number' => NULL,
                'qty' => 5.0,
                'price' => NULL,
                'created_at' => '2026-07-26 17:51:30',
                'updated_at' => '2026-07-26 17:51:30',
            ),
            34 => 
            array (
                'id' => 35,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 22,
                'imei_number' => NULL,
                'qty' => 5.0,
                'price' => NULL,
                'created_at' => '2026-07-26 17:51:30',
                'updated_at' => '2026-07-26 17:51:30',
            ),
            35 => 
            array (
                'id' => 36,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 21,
                'imei_number' => NULL,
                'qty' => 5.0,
                'price' => NULL,
                'created_at' => '2026-07-26 17:51:30',
                'updated_at' => '2026-07-26 17:51:30',
            ),
            36 => 
            array (
                'id' => 37,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 20,
                'imei_number' => NULL,
                'qty' => 15.0,
                'price' => NULL,
                'created_at' => '2026-07-26 17:51:30',
                'updated_at' => '2026-07-26 17:51:30',
            ),
            37 => 
            array (
                'id' => 38,
                'product_id' => 7,
                'product_batch_id' => NULL,
                'warehouse_id' => 1,
                'variant_id' => 11,
                'imei_number' => NULL,
                'qty' => 5.0,
                'price' => NULL,
                'created_at' => '2026-07-26 17:51:30',
                'updated_at' => '2026-07-26 17:51:30',
            ),
            38 => 
            array (
                'id' => 39,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 5,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => NULL,
                'created_at' => '2026-07-26 19:24:48',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            39 => 
            array (
                'id' => 40,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 6,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => NULL,
                'created_at' => '2026-07-26 19:24:48',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            40 => 
            array (
                'id' => 41,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 7,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => NULL,
                'created_at' => '2026-07-26 19:24:48',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            41 => 
            array (
                'id' => 42,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 8,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => NULL,
                'created_at' => '2026-07-26 19:24:48',
                'updated_at' => '2026-07-26 19:24:48',
            ),
            42 => 
            array (
                'id' => 43,
                'product_id' => 5,
                'product_batch_id' => NULL,
                'warehouse_id' => 2,
                'variant_id' => 9,
                'imei_number' => NULL,
                'qty' => 0.0,
                'price' => NULL,
                'created_at' => '2026-07-26 19:24:48',
                'updated_at' => '2026-07-26 19:24:48',
            ),
        ));
        
        
    }
}