<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductPurchasesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_purchases')->delete();
        
        \DB::table('product_purchases')->insert(array (
            0 => 
            array (
                'id' => 1,
                'purchase_id' => 1,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 8,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            1 => 
            array (
                'id' => 2,
                'purchase_id' => 1,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 7,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            2 => 
            array (
                'id' => 3,
                'purchase_id' => 1,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 6,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            3 => 
            array (
                'id' => 4,
                'purchase_id' => 1,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 5,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            4 => 
            array (
                'id' => 5,
                'purchase_id' => 1,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 33,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            5 => 
            array (
                'id' => 6,
                'purchase_id' => 1,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 46,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            6 => 
            array (
                'id' => 7,
                'purchase_id' => 1,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 45,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            7 => 
            array (
                'id' => 8,
                'purchase_id' => 1,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 44,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            8 => 
            array (
                'id' => 9,
                'purchase_id' => 1,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 43,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            9 => 
            array (
                'id' => 10,
                'purchase_id' => 1,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 42,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            10 => 
            array (
                'id' => 11,
                'purchase_id' => 1,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 41,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            11 => 
            array (
                'id' => 12,
                'purchase_id' => 1,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 40,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            12 => 
            array (
                'id' => 13,
                'purchase_id' => 1,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 39,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            13 => 
            array (
                'id' => 14,
                'purchase_id' => 1,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 38,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            14 => 
            array (
                'id' => 15,
                'purchase_id' => 1,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 37,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            15 => 
            array (
                'id' => 16,
                'purchase_id' => 1,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 36,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            16 => 
            array (
                'id' => 17,
                'purchase_id' => 1,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 35,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            17 => 
            array (
                'id' => 18,
                'purchase_id' => 1,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 34,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            18 => 
            array (
                'id' => 19,
                'purchase_id' => 1,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 33,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            19 => 
            array (
                'id' => 20,
                'purchase_id' => 1,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 32,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            20 => 
            array (
                'id' => 21,
                'purchase_id' => 1,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 31,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            21 => 
            array (
                'id' => 22,
                'purchase_id' => 1,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 30,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            22 => 
            array (
                'id' => 23,
                'purchase_id' => 1,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 29,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            23 => 
            array (
                'id' => 24,
                'purchase_id' => 1,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 28,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            24 => 
            array (
                'id' => 25,
                'purchase_id' => 1,
                'product_id' => 1,
                'qty' => 2.0,
                'recieved' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1000.0,
                'variant_id' => NULL,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 600.0,
                'created_at' => '2026-08-22 13:41:03',
                'updated_at' => '2026-08-22 13:41:03',
            ),
            25 => 
            array (
                'id' => 26,
                'purchase_id' => 2,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 46,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
            ),
            26 => 
            array (
                'id' => 27,
                'purchase_id' => 2,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 45,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
            ),
            27 => 
            array (
                'id' => 28,
                'purchase_id' => 2,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 44,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
            ),
            28 => 
            array (
                'id' => 29,
                'purchase_id' => 2,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 43,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
            ),
            29 => 
            array (
                'id' => 30,
                'purchase_id' => 2,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 42,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
            ),
            30 => 
            array (
                'id' => 31,
                'purchase_id' => 2,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 41,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
            ),
            31 => 
            array (
                'id' => 32,
                'purchase_id' => 2,
                'product_id' => 4,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 200.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 200.0,
                'variant_id' => 40,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 300.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
            ),
            32 => 
            array (
                'id' => 33,
                'purchase_id' => 2,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 8,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:15',
            ),
            33 => 
            array (
                'id' => 34,
                'purchase_id' => 2,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 7,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            34 => 
            array (
                'id' => 35,
                'purchase_id' => 2,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 6,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            35 => 
            array (
                'id' => 36,
                'purchase_id' => 2,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 5,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            36 => 
            array (
                'id' => 37,
                'purchase_id' => 2,
                'product_id' => 5,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 33,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 350.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            37 => 
            array (
                'id' => 38,
                'purchase_id' => 2,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 39,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            38 => 
            array (
                'id' => 39,
                'purchase_id' => 2,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 38,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            39 => 
            array (
                'id' => 40,
                'purchase_id' => 2,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 37,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            40 => 
            array (
                'id' => 41,
                'purchase_id' => 2,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 36,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            41 => 
            array (
                'id' => 42,
                'purchase_id' => 2,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 35,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            42 => 
            array (
                'id' => 43,
                'purchase_id' => 2,
                'product_id' => 3,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 300.0,
                'variant_id' => 34,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 1000.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            43 => 
            array (
                'id' => 44,
                'purchase_id' => 2,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 33,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            44 => 
            array (
                'id' => 45,
                'purchase_id' => 2,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 32,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            45 => 
            array (
                'id' => 46,
                'purchase_id' => 2,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 31,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            46 => 
            array (
                'id' => 47,
                'purchase_id' => 2,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 30,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            47 => 
            array (
                'id' => 48,
                'purchase_id' => 2,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 29,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            48 => 
            array (
                'id' => 49,
                'purchase_id' => 2,
                'product_id' => 2,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => 28,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 700.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
            49 => 
            array (
                'id' => 50,
                'purchase_id' => 2,
                'product_id' => 1,
                'qty' => 1.0,
                'recieved' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 500.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 500.0,
                'variant_id' => NULL,
                'product_batch_id' => NULL,
                'imei_number' => NULL,
                'selling_price' => 600.0,
                'created_at' => '2026-08-22 15:42:15',
                'updated_at' => '2026-08-22 15:42:16',
            ),
        ));
        
        
    }
}