<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductTransferTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('product_transfer')->delete();
        
        \DB::table('product_transfer')->insert(array (
            0 => 
            array (
                'id' => 1,
                'transfer_id' => 1,
                'product_id' => 648,
                'product_batch_id' => NULL,
                'variant_id' => 57,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 580.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 580.0,
                'created_at' => '2025-01-27 18:29:44',
                'updated_at' => '2025-01-27 18:29:44',
            ),
            1 => 
            array (
                'id' => 2,
                'transfer_id' => 2,
                'product_id' => 634,
                'product_batch_id' => NULL,
                'variant_id' => 21,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1150.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1150.0,
                'created_at' => '2025-01-27 18:33:02',
                'updated_at' => '2025-01-27 18:33:02',
            ),
            2 => 
            array (
                'id' => 3,
                'transfer_id' => 3,
                'product_id' => 627,
                'product_batch_id' => NULL,
                'variant_id' => 24,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2380.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2380.0,
                'created_at' => '2025-01-27 18:35:13',
                'updated_at' => '2025-01-27 18:35:13',
            ),
            3 => 
            array (
                'id' => 4,
                'transfer_id' => 4,
                'product_id' => 648,
                'product_batch_id' => NULL,
                'variant_id' => 57,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 580.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 580.0,
                'created_at' => '2025-01-27 18:44:15',
                'updated_at' => '2025-01-27 18:44:15',
            ),
            4 => 
            array (
                'id' => 5,
                'transfer_id' => 5,
                'product_id' => 626,
                'product_batch_id' => NULL,
                'variant_id' => 74,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 730.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 730.0,
                'created_at' => '2025-01-27 18:45:45',
                'updated_at' => '2025-01-27 18:45:45',
            ),
            5 => 
            array (
                'id' => 6,
                'transfer_id' => 6,
                'product_id' => 646,
                'product_batch_id' => NULL,
                'variant_id' => 40,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1250.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1250.0,
                'created_at' => '2025-01-27 18:51:55',
                'updated_at' => '2025-01-27 18:51:55',
            ),
            6 => 
            array (
                'id' => 7,
                'transfer_id' => 6,
                'product_id' => 646,
                'product_batch_id' => NULL,
                'variant_id' => 39,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1250.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1250.0,
                'created_at' => '2025-01-27 18:51:55',
                'updated_at' => '2025-01-27 18:51:55',
            ),
            7 => 
            array (
                'id' => 8,
                'transfer_id' => 6,
                'product_id' => 616,
                'product_batch_id' => NULL,
                'variant_id' => 10,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-27 18:51:55',
                'updated_at' => '2025-01-27 18:51:55',
            ),
            8 => 
            array (
                'id' => 9,
                'transfer_id' => 6,
                'product_id' => 629,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1700.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1700.0,
                'created_at' => '2025-01-27 18:51:55',
                'updated_at' => '2025-01-27 18:51:55',
            ),
            9 => 
            array (
                'id' => 10,
                'transfer_id' => 7,
                'product_id' => 617,
                'product_batch_id' => NULL,
                'variant_id' => 32,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-28 16:51:15',
                'updated_at' => '2025-01-28 16:51:15',
            ),
            10 => 
            array (
                'id' => 11,
                'transfer_id' => 8,
                'product_id' => 616,
                'product_batch_id' => NULL,
                'variant_id' => 7,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-28 16:54:59',
                'updated_at' => '2025-01-28 16:54:59',
            ),
            11 => 
            array (
                'id' => 12,
                'transfer_id' => 9,
                'product_id' => 473,
                'product_batch_id' => NULL,
                'variant_id' => 352,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 760.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 760.0,
                'created_at' => '2025-01-28 18:53:32',
                'updated_at' => '2025-01-28 18:53:32',
            ),
            12 => 
            array (
                'id' => 13,
                'transfer_id' => 10,
                'product_id' => 473,
                'product_batch_id' => NULL,
                'variant_id' => 351,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 760.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 760.0,
                'created_at' => '2025-01-28 18:57:55',
                'updated_at' => '2025-01-28 18:57:55',
            ),
            13 => 
            array (
                'id' => 14,
                'transfer_id' => 10,
                'product_id' => 473,
                'product_batch_id' => NULL,
                'variant_id' => 353,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 760.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 760.0,
                'created_at' => '2025-01-28 18:57:55',
                'updated_at' => '2025-01-28 18:57:55',
            ),
            14 => 
            array (
                'id' => 15,
                'transfer_id' => 10,
                'product_id' => 473,
                'product_batch_id' => NULL,
                'variant_id' => 354,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 760.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 760.0,
                'created_at' => '2025-01-28 18:57:55',
                'updated_at' => '2025-01-28 18:57:55',
            ),
            15 => 
            array (
                'id' => 16,
                'transfer_id' => 10,
                'product_id' => 473,
                'product_batch_id' => NULL,
                'variant_id' => 355,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 760.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 760.0,
                'created_at' => '2025-01-28 18:57:55',
                'updated_at' => '2025-01-28 18:57:55',
            ),
            16 => 
            array (
                'id' => 17,
                'transfer_id' => 10,
                'product_id' => 473,
                'product_batch_id' => NULL,
                'variant_id' => 388,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 760.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 760.0,
                'created_at' => '2025-01-28 18:57:55',
                'updated_at' => '2025-01-28 18:57:55',
            ),
            17 => 
            array (
                'id' => 18,
                'transfer_id' => 11,
                'product_id' => 642,
                'product_batch_id' => NULL,
                'variant_id' => 66,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1175.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1175.0,
                'created_at' => '2025-01-28 19:00:19',
                'updated_at' => '2025-01-28 19:00:19',
            ),
            18 => 
            array (
                'id' => 19,
                'transfer_id' => 12,
                'product_id' => 557,
                'product_batch_id' => NULL,
                'variant_id' => 179,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 594.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 594.0,
                'created_at' => '2025-01-28 19:28:40',
                'updated_at' => '2025-01-28 19:28:40',
            ),
            19 => 
            array (
                'id' => 20,
                'transfer_id' => 13,
                'product_id' => 515,
                'product_batch_id' => NULL,
                'variant_id' => 602,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 645.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 645.0,
                'created_at' => '2025-01-30 14:23:10',
                'updated_at' => '2025-01-30 14:23:10',
            ),
            20 => 
            array (
                'id' => 21,
                'transfer_id' => 14,
                'product_id' => 762,
                'product_batch_id' => NULL,
                'variant_id' => 248,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1120.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1120.0,
                'created_at' => '2025-01-30 17:41:53',
                'updated_at' => '2025-01-30 17:41:53',
            ),
        ));
        
        
    }
}