<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PurchaseProductReturnTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('purchase_product_return')->delete();
        
        \DB::table('purchase_product_return')->insert(array (
            0 => 
            array (
                'id' => 1,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 355,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            1 => 
            array (
                'id' => 2,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 355,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            2 => 
            array (
                'id' => 3,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 355,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            3 => 
            array (
                'id' => 4,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 355,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            4 => 
            array (
                'id' => 5,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 352,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            5 => 
            array (
                'id' => 6,
                'return_id' => 2,
                'product_id' => 14,
                'product_batch_id' => NULL,
                'variant_id' => 35,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3200.0,
                'created_at' => '2025-01-23 16:22:55',
                'updated_at' => '2025-01-23 16:22:55',
            ),
            6 => 
            array (
                'id' => 7,
                'return_id' => 2,
                'product_id' => 14,
                'product_batch_id' => NULL,
                'variant_id' => 34,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3200.0,
                'created_at' => '2025-01-23 16:22:55',
                'updated_at' => '2025-01-23 16:22:55',
            ),
            7 => 
            array (
                'id' => 8,
                'return_id' => 2,
                'product_id' => 14,
                'product_batch_id' => NULL,
                'variant_id' => 33,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3200.0,
                'created_at' => '2025-01-23 16:22:55',
                'updated_at' => '2025-01-23 16:22:55',
            ),
            8 => 
            array (
                'id' => 9,
                'return_id' => 2,
                'product_id' => 14,
                'product_batch_id' => NULL,
                'variant_id' => 32,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3200.0,
                'created_at' => '2025-01-23 16:22:55',
                'updated_at' => '2025-01-23 16:22:55',
            ),
            9 => 
            array (
                'id' => 10,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 20,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            10 => 
            array (
                'id' => 11,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 19,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            11 => 
            array (
                'id' => 12,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 18,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            12 => 
            array (
                'id' => 13,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            13 => 
            array (
                'id' => 14,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            14 => 
            array (
                'id' => 15,
                'return_id' => 4,
                'product_id' => 386,
                'product_batch_id' => NULL,
                'variant_id' => 395,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-25 18:52:21',
                'updated_at' => '2025-01-25 18:52:21',
            ),
            15 => 
            array (
                'id' => 16,
                'return_id' => 5,
                'product_id' => 123,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 760.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 760.0,
                'created_at' => '2025-05-07 18:07:35',
                'updated_at' => '2025-05-07 18:07:35',
            ),
            16 => 
            array (
                'id' => 17,
                'return_id' => 6,
                'product_id' => 574,
                'product_batch_id' => NULL,
                'variant_id' => 353,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 684.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 684.0,
                'created_at' => '2025-05-07 18:08:43',
                'updated_at' => '2025-05-07 18:08:43',
            ),
            17 => 
            array (
                'id' => 18,
                'return_id' => 7,
                'product_id' => 339,
                'product_batch_id' => NULL,
                'variant_id' => 18,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 788.4,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 788.4,
                'created_at' => '2025-05-07 18:09:58',
                'updated_at' => '2025-05-07 18:09:58',
            ),
            18 => 
            array (
                'id' => 19,
                'return_id' => 8,
                'product_id' => 136,
                'product_batch_id' => NULL,
                'variant_id' => 59,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:10:44',
                'updated_at' => '2025-05-07 18:10:44',
            ),
            19 => 
            array (
                'id' => 20,
                'return_id' => 8,
                'product_id' => 136,
                'product_batch_id' => NULL,
                'variant_id' => 42,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:10:44',
                'updated_at' => '2025-05-07 18:10:44',
            ),
            20 => 
            array (
                'id' => 21,
                'return_id' => 8,
                'product_id' => 136,
                'product_batch_id' => NULL,
                'variant_id' => 41,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:10:44',
                'updated_at' => '2025-05-07 18:10:44',
            ),
            21 => 
            array (
                'id' => 22,
                'return_id' => 8,
                'product_id' => 136,
                'product_batch_id' => NULL,
                'variant_id' => 40,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:10:44',
                'updated_at' => '2025-05-07 18:10:44',
            ),
            22 => 
            array (
                'id' => 23,
                'return_id' => 8,
                'product_id' => 136,
                'product_batch_id' => NULL,
                'variant_id' => 39,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:10:44',
                'updated_at' => '2025-05-07 18:10:44',
            ),
            23 => 
            array (
                'id' => 24,
                'return_id' => 8,
                'product_id' => 136,
                'product_batch_id' => NULL,
                'variant_id' => 38,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:10:44',
                'updated_at' => '2025-05-07 18:10:44',
            ),
            24 => 
            array (
                'id' => 25,
                'return_id' => 9,
                'product_id' => 117,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:11:32',
                'updated_at' => '2025-05-07 18:11:32',
            ),
            25 => 
            array (
                'id' => 26,
                'return_id' => 9,
                'product_id' => 117,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:11:32',
                'updated_at' => '2025-05-07 18:11:32',
            ),
            26 => 
            array (
                'id' => 27,
                'return_id' => 9,
                'product_id' => 117,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:11:32',
                'updated_at' => '2025-05-07 18:11:32',
            ),
            27 => 
            array (
                'id' => 28,
                'return_id' => 9,
                'product_id' => 117,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:11:32',
                'updated_at' => '2025-05-07 18:11:32',
            ),
            28 => 
            array (
                'id' => 29,
                'return_id' => 9,
                'product_id' => 117,
                'product_batch_id' => NULL,
                'variant_id' => 54,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:11:32',
                'updated_at' => '2025-05-07 18:11:32',
            ),
            29 => 
            array (
                'id' => 30,
                'return_id' => 9,
                'product_id' => 117,
                'product_batch_id' => NULL,
                'variant_id' => 53,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-07 18:11:32',
                'updated_at' => '2025-05-07 18:11:32',
            ),
            30 => 
            array (
                'id' => 34,
                'return_id' => 13,
                'product_id' => 473,
                'product_batch_id' => NULL,
                'variant_id' => 352,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 760.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 760.0,
                'created_at' => '2025-05-12 19:11:51',
                'updated_at' => '2025-05-12 19:11:51',
            ),
            31 => 
            array (
                'id' => 35,
                'return_id' => 14,
                'product_id' => 312,
                'product_batch_id' => NULL,
                'variant_id' => 181,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-12 19:16:23',
                'updated_at' => '2025-05-12 19:16:23',
            ),
            32 => 
            array (
                'id' => 36,
                'return_id' => 15,
                'product_id' => 498,
                'product_batch_id' => NULL,
                'variant_id' => 160,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1149.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1149.0,
                'created_at' => '2025-05-12 19:18:26',
                'updated_at' => '2025-05-12 19:18:26',
            ),
            33 => 
            array (
                'id' => 37,
                'return_id' => 16,
                'product_id' => 158,
                'product_batch_id' => NULL,
                'variant_id' => 181,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2152.0,
                'created_at' => '2025-05-12 19:19:37',
                'updated_at' => '2025-05-12 19:19:37',
            ),
            34 => 
            array (
                'id' => 38,
                'return_id' => 17,
                'product_id' => 87,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 684.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 684.0,
                'created_at' => '2025-05-12 19:22:53',
                'updated_at' => '2025-05-12 19:22:53',
            ),
            35 => 
            array (
                'id' => 39,
                'return_id' => 18,
                'product_id' => 849,
                'product_batch_id' => NULL,
                'variant_id' => 206,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1005.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2010.0,
                'created_at' => '2025-05-12 19:24:56',
                'updated_at' => '2025-05-12 19:24:56',
            ),
            36 => 
            array (
                'id' => 40,
                'return_id' => 19,
                'product_id' => 848,
                'product_batch_id' => NULL,
                'variant_id' => 70,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 19:31:26',
                'updated_at' => '2025-05-12 19:31:26',
            ),
            37 => 
            array (
                'id' => 41,
                'return_id' => 19,
                'product_id' => 848,
                'product_batch_id' => NULL,
                'variant_id' => 69,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 19:31:26',
                'updated_at' => '2025-05-12 19:31:26',
            ),
            38 => 
            array (
                'id' => 42,
                'return_id' => 19,
                'product_id' => 848,
                'product_batch_id' => NULL,
                'variant_id' => 68,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 19:31:26',
                'updated_at' => '2025-05-12 19:31:26',
            ),
            39 => 
            array (
                'id' => 43,
                'return_id' => 19,
                'product_id' => 848,
                'product_batch_id' => NULL,
                'variant_id' => 67,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 19:31:26',
                'updated_at' => '2025-05-12 19:31:26',
            ),
            40 => 
            array (
                'id' => 44,
                'return_id' => 19,
                'product_id' => 848,
                'product_batch_id' => NULL,
                'variant_id' => 66,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 19:31:26',
                'updated_at' => '2025-05-12 19:31:26',
            ),
            41 => 
            array (
                'id' => 45,
                'return_id' => 19,
                'product_id' => 848,
                'product_batch_id' => NULL,
                'variant_id' => 65,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 19:31:26',
                'updated_at' => '2025-05-12 19:31:26',
            ),
            42 => 
            array (
                'id' => 46,
                'return_id' => 20,
                'product_id' => 490,
                'product_batch_id' => NULL,
                'variant_id' => 162,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1149.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1149.0,
                'created_at' => '2025-05-12 19:33:42',
                'updated_at' => '2025-05-12 19:33:42',
            ),
            43 => 
            array (
                'id' => 47,
                'return_id' => 21,
                'product_id' => 486,
                'product_batch_id' => NULL,
                'variant_id' => 353,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 19:36:07',
                'updated_at' => '2025-05-12 19:36:07',
            ),
            44 => 
            array (
                'id' => 48,
                'return_id' => 22,
                'product_id' => 1058,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1076.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1076.0,
                'created_at' => '2025-05-12 19:44:00',
                'updated_at' => '2025-05-12 19:44:00',
            ),
            45 => 
            array (
                'id' => 49,
                'return_id' => 23,
                'product_id' => 1022,
                'product_batch_id' => NULL,
                'variant_id' => 6,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1508.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1508.0,
                'created_at' => '2025-05-12 19:54:50',
                'updated_at' => '2025-05-12 19:54:50',
            ),
            46 => 
            array (
                'id' => 50,
                'return_id' => 24,
                'product_id' => 279,
                'product_batch_id' => NULL,
                'variant_id' => 208,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1365.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1365.0,
                'created_at' => '2025-05-12 19:56:14',
                'updated_at' => '2025-05-12 19:56:14',
            ),
            47 => 
            array (
                'id' => 51,
                'return_id' => 24,
                'product_id' => 279,
                'product_batch_id' => NULL,
                'variant_id' => 207,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1365.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1365.0,
                'created_at' => '2025-05-12 19:56:14',
                'updated_at' => '2025-05-12 19:56:14',
            ),
            48 => 
            array (
                'id' => 52,
                'return_id' => 24,
                'product_id' => 279,
                'product_batch_id' => NULL,
                'variant_id' => 206,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1365.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1365.0,
                'created_at' => '2025-05-12 19:56:14',
                'updated_at' => '2025-05-12 19:56:14',
            ),
            49 => 
            array (
                'id' => 53,
                'return_id' => 24,
                'product_id' => 279,
                'product_batch_id' => NULL,
                'variant_id' => 209,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1365.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1365.0,
                'created_at' => '2025-05-12 19:56:14',
                'updated_at' => '2025-05-12 19:56:14',
            ),
            50 => 
            array (
                'id' => 54,
                'return_id' => 24,
                'product_id' => 279,
                'product_batch_id' => NULL,
                'variant_id' => 189,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1365.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1365.0,
                'created_at' => '2025-05-12 19:56:14',
                'updated_at' => '2025-05-12 19:56:14',
            ),
            51 => 
            array (
                'id' => 55,
                'return_id' => 24,
                'product_id' => 279,
                'product_batch_id' => NULL,
                'variant_id' => 188,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1365.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1365.0,
                'created_at' => '2025-05-12 19:56:14',
                'updated_at' => '2025-05-12 19:56:14',
            ),
            52 => 
            array (
                'id' => 57,
                'return_id' => 26,
                'product_id' => 1127,
                'product_batch_id' => NULL,
                'variant_id' => 23,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1300.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1300.0,
                'created_at' => '2025-05-12 20:07:07',
                'updated_at' => '2025-05-12 20:07:07',
            ),
            53 => 
            array (
                'id' => 58,
                'return_id' => 27,
                'product_id' => 709,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 630.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 630.0,
                'created_at' => '2025-05-12 20:10:34',
                'updated_at' => '2025-05-12 20:10:34',
            ),
            54 => 
            array (
                'id' => 59,
                'return_id' => 27,
                'product_id' => 709,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 630.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 630.0,
                'created_at' => '2025-05-12 20:10:34',
                'updated_at' => '2025-05-12 20:10:34',
            ),
            55 => 
            array (
                'id' => 60,
                'return_id' => 28,
                'product_id' => 215,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1220.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1220.0,
                'created_at' => '2025-05-12 20:19:31',
                'updated_at' => '2025-05-12 20:19:31',
            ),
            56 => 
            array (
                'id' => 61,
                'return_id' => 29,
                'product_id' => 721,
                'product_batch_id' => NULL,
                'variant_id' => 179,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 400.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 400.0,
                'created_at' => '2025-05-12 20:25:33',
                'updated_at' => '2025-05-12 20:25:33',
            ),
            57 => 
            array (
                'id' => 62,
                'return_id' => 30,
                'product_id' => 501,
                'product_batch_id' => NULL,
                'variant_id' => 327,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 615.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 615.0,
                'created_at' => '2025-05-12 20:27:07',
                'updated_at' => '2025-05-12 20:27:07',
            ),
            58 => 
            array (
                'id' => 63,
                'return_id' => 31,
                'product_id' => 450,
                'product_batch_id' => NULL,
                'variant_id' => 164,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 645.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 645.0,
                'created_at' => '2025-05-12 20:29:03',
                'updated_at' => '2025-05-12 20:29:03',
            ),
            59 => 
            array (
                'id' => 64,
                'return_id' => 32,
                'product_id' => 862,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:35:55',
                'updated_at' => '2025-05-12 20:35:55',
            ),
            60 => 
            array (
                'id' => 65,
                'return_id' => 32,
                'product_id' => 862,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:35:55',
                'updated_at' => '2025-05-12 20:35:55',
            ),
            61 => 
            array (
                'id' => 66,
                'return_id' => 32,
                'product_id' => 862,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:35:55',
                'updated_at' => '2025-05-12 20:35:55',
            ),
            62 => 
            array (
                'id' => 67,
                'return_id' => 32,
                'product_id' => 862,
                'product_batch_id' => NULL,
                'variant_id' => 54,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:35:55',
                'updated_at' => '2025-05-12 20:35:55',
            ),
            63 => 
            array (
                'id' => 68,
                'return_id' => 32,
                'product_id' => 862,
                'product_batch_id' => NULL,
                'variant_id' => 53,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:35:55',
                'updated_at' => '2025-05-12 20:35:55',
            ),
            64 => 
            array (
                'id' => 69,
                'return_id' => 33,
                'product_id' => 844,
                'product_batch_id' => NULL,
                'variant_id' => 59,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 20:36:50',
                'updated_at' => '2025-05-12 20:36:50',
            ),
            65 => 
            array (
                'id' => 70,
                'return_id' => 33,
                'product_id' => 844,
                'product_batch_id' => NULL,
                'variant_id' => 42,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 20:36:50',
                'updated_at' => '2025-05-12 20:36:50',
            ),
            66 => 
            array (
                'id' => 71,
                'return_id' => 33,
                'product_id' => 844,
                'product_batch_id' => NULL,
                'variant_id' => 41,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 20:36:50',
                'updated_at' => '2025-05-12 20:36:50',
            ),
            67 => 
            array (
                'id' => 72,
                'return_id' => 33,
                'product_id' => 844,
                'product_batch_id' => NULL,
                'variant_id' => 40,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 20:36:50',
                'updated_at' => '2025-05-12 20:36:50',
            ),
            68 => 
            array (
                'id' => 73,
                'return_id' => 33,
                'product_id' => 844,
                'product_batch_id' => NULL,
                'variant_id' => 39,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 20:36:50',
                'updated_at' => '2025-05-12 20:36:50',
            ),
            69 => 
            array (
                'id' => 74,
                'return_id' => 33,
                'product_id' => 844,
                'product_batch_id' => NULL,
                'variant_id' => 38,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 860.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 860.0,
                'created_at' => '2025-05-12 20:36:50',
                'updated_at' => '2025-05-12 20:36:50',
            ),
            70 => 
            array (
                'id' => 75,
                'return_id' => 34,
                'product_id' => 164,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 716.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 716.0,
                'created_at' => '2025-05-12 20:37:26',
                'updated_at' => '2025-05-12 20:37:26',
            ),
            71 => 
            array (
                'id' => 76,
                'return_id' => 34,
                'product_id' => 164,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 716.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 716.0,
                'created_at' => '2025-05-12 20:37:26',
                'updated_at' => '2025-05-12 20:37:26',
            ),
            72 => 
            array (
                'id' => 77,
                'return_id' => 34,
                'product_id' => 164,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 716.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 716.0,
                'created_at' => '2025-05-12 20:37:26',
                'updated_at' => '2025-05-12 20:37:26',
            ),
            73 => 
            array (
                'id' => 78,
                'return_id' => 34,
                'product_id' => 164,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 716.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 716.0,
                'created_at' => '2025-05-12 20:37:26',
                'updated_at' => '2025-05-12 20:37:26',
            ),
            74 => 
            array (
                'id' => 79,
                'return_id' => 34,
                'product_id' => 164,
                'product_batch_id' => NULL,
                'variant_id' => 54,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 716.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 716.0,
                'created_at' => '2025-05-12 20:37:26',
                'updated_at' => '2025-05-12 20:37:26',
            ),
            75 => 
            array (
                'id' => 80,
                'return_id' => 34,
                'product_id' => 164,
                'product_batch_id' => NULL,
                'variant_id' => 53,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 716.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 716.0,
                'created_at' => '2025-05-12 20:37:26',
                'updated_at' => '2025-05-12 20:37:26',
            ),
            76 => 
            array (
                'id' => 81,
                'return_id' => 35,
                'product_id' => 884,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:04',
                'updated_at' => '2025-05-12 20:38:04',
            ),
            77 => 
            array (
                'id' => 82,
                'return_id' => 35,
                'product_id' => 884,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:04',
                'updated_at' => '2025-05-12 20:38:04',
            ),
            78 => 
            array (
                'id' => 83,
                'return_id' => 35,
                'product_id' => 884,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:04',
                'updated_at' => '2025-05-12 20:38:04',
            ),
            79 => 
            array (
                'id' => 84,
                'return_id' => 35,
                'product_id' => 884,
                'product_batch_id' => NULL,
                'variant_id' => 54,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:04',
                'updated_at' => '2025-05-12 20:38:04',
            ),
            80 => 
            array (
                'id' => 85,
                'return_id' => 35,
                'product_id' => 884,
                'product_batch_id' => NULL,
                'variant_id' => 53,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:04',
                'updated_at' => '2025-05-12 20:38:04',
            ),
            81 => 
            array (
                'id' => 86,
                'return_id' => 36,
                'product_id' => 875,
                'product_batch_id' => NULL,
                'variant_id' => 42,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:50',
                'updated_at' => '2025-05-12 20:38:50',
            ),
            82 => 
            array (
                'id' => 87,
                'return_id' => 36,
                'product_id' => 875,
                'product_batch_id' => NULL,
                'variant_id' => 41,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:50',
                'updated_at' => '2025-05-12 20:38:50',
            ),
            83 => 
            array (
                'id' => 88,
                'return_id' => 36,
                'product_id' => 875,
                'product_batch_id' => NULL,
                'variant_id' => 40,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:50',
                'updated_at' => '2025-05-12 20:38:50',
            ),
            84 => 
            array (
                'id' => 89,
                'return_id' => 36,
                'product_id' => 875,
                'product_batch_id' => NULL,
                'variant_id' => 39,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:50',
                'updated_at' => '2025-05-12 20:38:50',
            ),
            85 => 
            array (
                'id' => 90,
                'return_id' => 36,
                'product_id' => 875,
                'product_batch_id' => NULL,
                'variant_id' => 38,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 882.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 882.0,
                'created_at' => '2025-05-12 20:38:50',
                'updated_at' => '2025-05-12 20:38:50',
            ),
            86 => 
            array (
                'id' => 91,
                'return_id' => 37,
                'product_id' => 883,
                'product_batch_id' => NULL,
                'variant_id' => 221,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:44:59',
                'updated_at' => '2025-05-12 20:44:59',
            ),
            87 => 
            array (
                'id' => 92,
                'return_id' => 37,
                'product_id' => 883,
                'product_batch_id' => NULL,
                'variant_id' => 220,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:44:59',
                'updated_at' => '2025-05-12 20:44:59',
            ),
            88 => 
            array (
                'id' => 93,
                'return_id' => 37,
                'product_id' => 883,
                'product_batch_id' => NULL,
                'variant_id' => 219,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:44:59',
                'updated_at' => '2025-05-12 20:44:59',
            ),
            89 => 
            array (
                'id' => 94,
                'return_id' => 37,
                'product_id' => 883,
                'product_batch_id' => NULL,
                'variant_id' => 218,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:44:59',
                'updated_at' => '2025-05-12 20:44:59',
            ),
            90 => 
            array (
                'id' => 95,
                'return_id' => 37,
                'product_id' => 883,
                'product_batch_id' => NULL,
                'variant_id' => 217,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:44:59',
                'updated_at' => '2025-05-12 20:44:59',
            ),
            91 => 
            array (
                'id' => 96,
                'return_id' => 38,
                'product_id' => 869,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:51:06',
                'updated_at' => '2025-05-12 20:51:06',
            ),
            92 => 
            array (
                'id' => 97,
                'return_id' => 38,
                'product_id' => 869,
                'product_batch_id' => NULL,
                'variant_id' => 26,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:51:06',
                'updated_at' => '2025-05-12 20:51:06',
            ),
            93 => 
            array (
                'id' => 98,
                'return_id' => 38,
                'product_id' => 869,
                'product_batch_id' => NULL,
                'variant_id' => 55,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:51:06',
                'updated_at' => '2025-05-12 20:51:06',
            ),
            94 => 
            array (
                'id' => 99,
                'return_id' => 38,
                'product_id' => 869,
                'product_batch_id' => NULL,
                'variant_id' => 54,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:51:06',
                'updated_at' => '2025-05-12 20:51:06',
            ),
            95 => 
            array (
                'id' => 100,
                'return_id' => 38,
                'product_id' => 869,
                'product_batch_id' => NULL,
                'variant_id' => 53,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 975.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 975.0,
                'created_at' => '2025-05-12 20:51:06',
                'updated_at' => '2025-05-12 20:51:06',
            ),
            96 => 
            array (
                'id' => 101,
                'return_id' => 39,
                'product_id' => 618,
                'product_batch_id' => NULL,
                'variant_id' => 75,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-05-12 20:53:47',
                'updated_at' => '2025-05-12 20:53:47',
            ),
            97 => 
            array (
                'id' => 102,
                'return_id' => 39,
                'product_id' => 618,
                'product_batch_id' => NULL,
                'variant_id' => 74,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-05-12 20:53:47',
                'updated_at' => '2025-05-12 20:53:47',
            ),
            98 => 
            array (
                'id' => 103,
                'return_id' => 39,
                'product_id' => 618,
                'product_batch_id' => NULL,
                'variant_id' => 73,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-05-12 20:53:47',
                'updated_at' => '2025-05-12 20:53:47',
            ),
            99 => 
            array (
                'id' => 104,
                'return_id' => 39,
                'product_id' => 618,
                'product_batch_id' => NULL,
                'variant_id' => 72,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-05-12 20:53:47',
                'updated_at' => '2025-05-12 20:53:47',
            ),
            100 => 
            array (
                'id' => 105,
                'return_id' => 39,
                'product_id' => 618,
                'product_batch_id' => NULL,
                'variant_id' => 71,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-05-12 20:53:47',
                'updated_at' => '2025-05-12 20:53:47',
            ),
            101 => 
            array (
                'id' => 106,
                'return_id' => 40,
                'product_id' => 638,
                'product_batch_id' => NULL,
                'variant_id' => 11,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-05-12 20:54:18',
                'updated_at' => '2025-05-12 20:54:18',
            ),
            102 => 
            array (
                'id' => 107,
                'return_id' => 40,
                'product_id' => 638,
                'product_batch_id' => NULL,
                'variant_id' => 109,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-05-12 20:54:18',
                'updated_at' => '2025-05-12 20:54:18',
            ),
            103 => 
            array (
                'id' => 108,
                'return_id' => 40,
                'product_id' => 638,
                'product_batch_id' => NULL,
                'variant_id' => 108,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-05-12 20:54:18',
                'updated_at' => '2025-05-12 20:54:18',
            ),
            104 => 
            array (
                'id' => 109,
                'return_id' => 40,
                'product_id' => 638,
                'product_batch_id' => NULL,
                'variant_id' => 107,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-05-12 20:54:18',
                'updated_at' => '2025-05-12 20:54:18',
            ),
            105 => 
            array (
                'id' => 110,
                'return_id' => 40,
                'product_id' => 638,
                'product_batch_id' => NULL,
                'variant_id' => 106,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1290.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1290.0,
                'created_at' => '2025-05-12 20:54:18',
                'updated_at' => '2025-05-12 20:54:18',
            ),
        ));
        
        
    }
}