<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PurchaseProductReturnTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('purchase_product_return')->delete();
        
        \DB::table('purchase_product_return')->insert(array (
            0 => 
            array (
                'id' => 1,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 355,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            1 => 
            array (
                'id' => 2,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 355,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            2 => 
            array (
                'id' => 3,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 355,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            3 => 
            array (
                'id' => 4,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 355,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            4 => 
            array (
                'id' => 5,
                'return_id' => 1,
                'product_id' => 388,
                'product_batch_id' => NULL,
                'variant_id' => 352,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-14 16:37:56',
                'updated_at' => '2025-01-14 16:37:56',
            ),
            5 => 
            array (
                'id' => 6,
                'return_id' => 2,
                'product_id' => 14,
                'product_batch_id' => NULL,
                'variant_id' => 35,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3200.0,
                'created_at' => '2025-01-23 16:22:55',
                'updated_at' => '2025-01-23 16:22:55',
            ),
            6 => 
            array (
                'id' => 7,
                'return_id' => 2,
                'product_id' => 14,
                'product_batch_id' => NULL,
                'variant_id' => 34,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3200.0,
                'created_at' => '2025-01-23 16:22:55',
                'updated_at' => '2025-01-23 16:22:55',
            ),
            7 => 
            array (
                'id' => 8,
                'return_id' => 2,
                'product_id' => 14,
                'product_batch_id' => NULL,
                'variant_id' => 33,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3200.0,
                'created_at' => '2025-01-23 16:22:55',
                'updated_at' => '2025-01-23 16:22:55',
            ),
            8 => 
            array (
                'id' => 9,
                'return_id' => 2,
                'product_id' => 14,
                'product_batch_id' => NULL,
                'variant_id' => 32,
                'imei_number' => NULL,
                'qty' => 2.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 3200.0,
                'created_at' => '2025-01-23 16:22:55',
                'updated_at' => '2025-01-23 16:22:55',
            ),
            9 => 
            array (
                'id' => 10,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 20,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            10 => 
            array (
                'id' => 11,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 19,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            11 => 
            array (
                'id' => 12,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 18,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            12 => 
            array (
                'id' => 13,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 17,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            13 => 
            array (
                'id' => 14,
                'return_id' => 3,
                'product_id' => 16,
                'product_batch_id' => NULL,
                'variant_id' => 16,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 1600.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 1600.0,
                'created_at' => '2025-01-23 16:24:30',
                'updated_at' => '2025-01-23 16:24:30',
            ),
            14 => 
            array (
                'id' => 15,
                'return_id' => 4,
                'product_id' => 386,
                'product_batch_id' => NULL,
                'variant_id' => 395,
                'imei_number' => NULL,
                'qty' => 1.0,
                'purchase_unit_id' => 1,
                'net_unit_cost' => 2075.0,
                'discount' => 0.0,
                'tax_rate' => 0.0,
                'tax' => 0.0,
                'total' => 2075.0,
                'created_at' => '2025-01-25 18:52:21',
                'updated_at' => '2025-01-25 18:52:21',
            ),
        ));
        
        
    }
}