<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ReturnsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('returns')->delete();
        
        \DB::table('returns')->insert(array (
            0 => 
            array (
                'id' => 1,
                'reference_no' => 'rr-20241227-053128',
                'user_id' => 1,
                'sale_id' => 5,
                'cash_register_id' => 1,
                'customer_id' => 1,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1890.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1890.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2024-12-27 17:31:28',
                'updated_at' => '2024-12-27 17:31:28',
            ),
            1 => 
            array (
                'id' => 2,
                'reference_no' => 'rr-20241231-012434',
                'user_id' => 1,
                'sale_id' => 57,
                'cash_register_id' => 1,
                'customer_id' => 43,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1341.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1341.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2024-12-31 13:24:34',
                'updated_at' => '2024-12-31 13:24:34',
            ),
            2 => 
            array (
                'id' => 3,
                'reference_no' => 'rr-20241231-025905',
                'user_id' => 1,
                'sale_id' => 64,
                'cash_register_id' => 1,
                'customer_id' => 1,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1971.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1971.0,
                'document' => NULL,
                'return_note' => '1500 TK',
                'staff_note' => NULL,
                'created_at' => '2024-12-31 14:59:05',
                'updated_at' => '2024-12-31 14:59:05',
            ),
            3 => 
            array (
                'id' => 4,
                'reference_no' => 'rr-20250102-013846',
                'user_id' => 1,
                'sale_id' => 96,
                'cash_register_id' => 1,
                'customer_id' => 77,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 695.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 695.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-02 13:38:46',
                'updated_at' => '2025-01-02 13:38:46',
            ),
            4 => 
            array (
                'id' => 5,
                'reference_no' => 'rr-20250102-052707',
                'user_id' => 1,
                'sale_id' => 37,
                'cash_register_id' => 1,
                'customer_id' => 28,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 2190.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 2190.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-02 17:27:07',
                'updated_at' => '2025-01-02 17:27:07',
            ),
            5 => 
            array (
                'id' => 6,
                'reference_no' => 'rr-20250102-075703',
                'user_id' => 1,
                'sale_id' => 51,
                'cash_register_id' => 1,
                'customer_id' => 1,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1341.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1341.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-02 19:57:03',
                'updated_at' => '2025-01-02 19:57:03',
            ),
            6 => 
            array (
                'id' => 7,
                'reference_no' => 'rr-20250104-071348',
                'user_id' => 1,
                'sale_id' => 111,
                'cash_register_id' => 1,
                'customer_id' => 89,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 2490.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 2490.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-04 19:13:48',
                'updated_at' => '2025-01-04 19:13:48',
            ),
            7 => 
            array (
                'id' => 8,
                'reference_no' => 'rr-20250105-050223',
                'user_id' => 1,
                'sale_id' => 157,
                'cash_register_id' => 1,
                'customer_id' => 132,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1790.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1790.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-05 17:02:23',
                'updated_at' => '2025-01-05 17:02:23',
            ),
            8 => 
            array (
                'id' => 9,
                'reference_no' => 'rr-20250105-063634',
                'user_id' => 1,
                'sale_id' => 126,
                'cash_register_id' => 1,
                'customer_id' => 105,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 2790.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 2790.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-05 18:36:34',
                'updated_at' => '2025-01-05 18:36:34',
            ),
            9 => 
            array (
                'id' => 10,
                'reference_no' => 'rr-20250109-073613',
                'user_id' => 1,
                'sale_id' => 247,
                'cash_register_id' => 1,
                'customer_id' => 205,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 2690.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 2690.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-09 19:36:13',
                'updated_at' => '2025-01-09 19:36:13',
            ),
            10 => 
            array (
                'id' => 17,
                'reference_no' => 'rr-20250112-071328',
                'user_id' => 1,
                'sale_id' => 191,
                'cash_register_id' => 1,
                'customer_id' => 163,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1290.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1290.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-12 19:13:28',
                'updated_at' => '2025-01-12 19:13:28',
            ),
            11 => 
            array (
                'id' => 18,
                'reference_no' => 'rr-20250115-035316',
                'user_id' => 1,
                'sale_id' => 238,
                'cash_register_id' => 1,
                'customer_id' => 197,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1055.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1055.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-15 15:53:16',
                'updated_at' => '2025-01-15 15:53:16',
            ),
            12 => 
            array (
                'id' => 19,
                'reference_no' => 'rr-20250115-070800',
                'user_id' => 1,
                'sale_id' => 340,
                'cash_register_id' => 1,
                'customer_id' => 286,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1290.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1290.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-15 19:08:00',
                'updated_at' => '2025-01-15 19:08:00',
            ),
            13 => 
            array (
                'id' => 20,
                'reference_no' => 'rr-20250116-012409',
                'user_id' => 1,
                'sale_id' => 348,
                'cash_register_id' => 1,
                'customer_id' => 294,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1990.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1990.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-16 13:24:09',
                'updated_at' => '2025-01-16 13:24:09',
            ),
            14 => 
            array (
                'id' => 21,
                'reference_no' => 'rr-20250116-080332',
                'user_id' => 1,
                'sale_id' => 360,
                'cash_register_id' => 1,
                'customer_id' => 304,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 2890.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 2890.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-16 20:03:32',
                'updated_at' => '2025-01-16 20:03:32',
            ),
            15 => 
            array (
                'id' => 22,
                'reference_no' => 'rr-20250118-041817',
                'user_id' => 1,
                'sale_id' => 386,
                'cash_register_id' => 1,
                'customer_id' => 328,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1490.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1490.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-18 16:18:17',
                'updated_at' => '2025-01-18 16:18:17',
            ),
            16 => 
            array (
                'id' => 23,
                'reference_no' => 'rr-20250119-071649',
                'user_id' => 1,
                'sale_id' => 407,
                'cash_register_id' => 1,
                'customer_id' => 344,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 3395.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 3395.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-19 19:16:49',
                'updated_at' => '2025-01-19 19:16:49',
            ),
            17 => 
            array (
                'id' => 24,
                'reference_no' => 'rr-20250121-053747',
                'user_id' => 1,
                'sale_id' => 419,
                'cash_register_id' => 1,
                'customer_id' => 355,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1495.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1495.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-21 17:37:47',
                'updated_at' => '2025-01-21 17:37:47',
            ),
            18 => 
            array (
                'id' => 25,
                'reference_no' => 'rr-20250121-071200',
                'user_id' => 1,
                'sale_id' => 427,
                'cash_register_id' => 1,
                'customer_id' => 362,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1990.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1990.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-21 19:12:00',
                'updated_at' => '2025-01-21 19:12:00',
            ),
            19 => 
            array (
                'id' => 26,
                'reference_no' => 'rr-20250125-061445',
                'user_id' => 1,
                'sale_id' => 54,
                'cash_register_id' => 1,
                'customer_id' => 40,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 855.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 855.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-25 18:14:45',
                'updated_at' => '2025-01-25 18:14:45',
            ),
            20 => 
            array (
                'id' => 27,
                'reference_no' => 'rr-20250126-010414',
                'user_id' => 1,
                'sale_id' => 504,
                'cash_register_id' => 1,
                'customer_id' => 434,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1550.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1550.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-26 13:04:14',
                'updated_at' => '2025-01-26 13:04:14',
            ),
            21 => 
            array (
                'id' => 28,
                'reference_no' => 'rr-20250126-053900',
                'user_id' => 1,
                'sale_id' => 429,
                'cash_register_id' => 1,
                'customer_id' => 364,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 795.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 795.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-26 17:39:00',
                'updated_at' => '2025-01-26 17:39:00',
            ),
            22 => 
            array (
                'id' => 29,
                'reference_no' => 'rr-20250126-061102',
                'user_id' => 1,
                'sale_id' => 528,
                'cash_register_id' => 1,
                'customer_id' => 40,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 950.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 855.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-26 18:11:02',
                'updated_at' => '2025-01-26 18:11:02',
            ),
            23 => 
            array (
                'id' => 30,
                'reference_no' => 'rr-20250128-051655',
                'user_id' => 1,
                'sale_id' => 538,
                'cash_register_id' => 1,
                'customer_id' => 256,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1495.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1495.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-28 17:16:55',
                'updated_at' => '2025-01-28 17:16:55',
            ),
            24 => 
            array (
                'id' => 31,
                'reference_no' => 'rr-20250130-112850',
                'user_id' => 1,
                'sale_id' => 546,
                'cash_register_id' => 1,
                'customer_id' => 471,
                'warehouse_id' => 1,
                'biller_id' => 2,
                'account_id' => 1,
                'currency_id' => NULL,
                'exchange_rate' => NULL,
                'item' => 1,
                'total_qty' => 1.0,
                'total_discount' => 0.0,
                'total_tax' => 0.0,
                'total_price' => 1495.0,
                'order_tax_rate' => 0.0,
                'order_tax' => 0.0,
                'grand_total' => 1495.0,
                'document' => NULL,
                'return_note' => NULL,
                'staff_note' => NULL,
                'created_at' => '2025-01-30 11:28:50',
                'updated_at' => '2025-01-30 11:28:50',
            ),
        ));
        
        
    }
}