<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TransfersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('transfers')->delete();
        
        \DB::table('transfers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'reference_no' => 'tr-20250127-062944',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 580.0,
                'shipping_cost' => NULL,
                'grand_total' => 580.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:29:44',
            ),
            1 => 
            array (
                'id' => 2,
                'reference_no' => 'tr-20250127-063302',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1150.0,
                'shipping_cost' => NULL,
                'grand_total' => 1150.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:33:02',
            ),
            2 => 
            array (
                'id' => 3,
                'reference_no' => 'tr-20250127-063513',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 2380.0,
                'shipping_cost' => NULL,
                'grand_total' => 2380.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:35:13',
            ),
            3 => 
            array (
                'id' => 4,
                'reference_no' => 'tr-20250127-064415',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 580.0,
                'shipping_cost' => NULL,
                'grand_total' => 580.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:44:15',
            ),
            4 => 
            array (
                'id' => 5,
                'reference_no' => 'tr-20250127-064545',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 730.0,
                'shipping_cost' => NULL,
                'grand_total' => 730.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:45:45',
            ),
            5 => 
            array (
                'id' => 6,
                'reference_no' => 'tr-20250127-065155',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 4,
                'total_qty' => 4.0,
                'total_tax' => 0.0,
                'total_cost' => 5800.0,
                'shipping_cost' => NULL,
                'grand_total' => 5800.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 18:51:55',
                'updated_at' => '2025-01-27 18:51:55',
            ),
            6 => 
            array (
                'id' => 7,
                'reference_no' => 'tr-20250128-045115',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1600.0,
                'shipping_cost' => NULL,
                'grand_total' => 1600.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 16:51:15',
                'updated_at' => '2025-01-28 16:51:15',
            ),
            7 => 
            array (
                'id' => 8,
                'reference_no' => 'tr-20250128-045459',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1600.0,
                'shipping_cost' => NULL,
                'grand_total' => 1600.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 16:54:59',
                'updated_at' => '2025-01-28 16:54:59',
            ),
            8 => 
            array (
                'id' => 9,
                'reference_no' => 'tr-20250128-065332',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 760.0,
                'shipping_cost' => NULL,
                'grand_total' => 760.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 00:00:00',
                'updated_at' => '2025-01-28 18:53:32',
            ),
            9 => 
            array (
                'id' => 10,
                'reference_no' => 'tr-20250128-065755',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 5,
                'total_qty' => 5.0,
                'total_tax' => 0.0,
                'total_cost' => 3800.0,
                'shipping_cost' => NULL,
                'grand_total' => 3800.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 18:57:55',
                'updated_at' => '2025-01-28 18:57:55',
            ),
            10 => 
            array (
                'id' => 11,
                'reference_no' => 'tr-20250128-070019',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1175.0,
                'shipping_cost' => NULL,
                'grand_total' => 1175.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 00:00:00',
                'updated_at' => '2025-01-28 19:00:19',
            ),
            11 => 
            array (
                'id' => 12,
                'reference_no' => 'tr-20250128-072840',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 594.0,
                'shipping_cost' => NULL,
                'grand_total' => 594.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 19:28:40',
                'updated_at' => '2025-01-28 19:28:40',
            ),
            12 => 
            array (
                'id' => 13,
                'reference_no' => 'tr-20250130-022310',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 645.0,
                'shipping_cost' => NULL,
                'grand_total' => 645.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-30 00:00:00',
                'updated_at' => '2025-01-30 14:23:10',
            ),
            13 => 
            array (
                'id' => 14,
                'reference_no' => 'tr-20250130-054153',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1120.0,
                'shipping_cost' => NULL,
                'grand_total' => 1120.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-30 00:00:00',
                'updated_at' => '2025-01-30 17:41:53',
            ),
            14 => 
            array (
                'id' => 15,
                'reference_no' => 'tr-20250131-074952',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1800.0,
                'shipping_cost' => NULL,
                'grand_total' => 1800.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-31 00:00:00',
                'updated_at' => '2025-01-31 19:49:52',
            ),
            15 => 
            array (
                'id' => 16,
                'reference_no' => 'tr-20250131-075449',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 2,
                'total_qty' => 2.0,
                'total_tax' => 0.0,
                'total_cost' => 1290.0,
                'shipping_cost' => NULL,
                'grand_total' => 1290.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-31 00:00:00',
                'updated_at' => '2025-01-31 19:54:49',
            ),
            16 => 
            array (
                'id' => 17,
                'reference_no' => 'tr-20250201-033535',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 630.0,
                'shipping_cost' => NULL,
                'grand_total' => 630.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-01 15:35:35',
                'updated_at' => '2025-02-01 15:35:35',
            ),
            17 => 
            array (
                'id' => 18,
                'reference_no' => 'tr-20250201-041728',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 730.0,
                'shipping_cost' => NULL,
                'grand_total' => 730.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-01 00:00:00',
                'updated_at' => '2025-02-01 16:17:28',
            ),
            18 => 
            array (
                'id' => 19,
                'reference_no' => 'tr-20250201-053249',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 471.0,
                'shipping_cost' => NULL,
                'grand_total' => 471.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-01 00:00:00',
                'updated_at' => '2025-02-01 17:32:49',
            ),
            19 => 
            array (
                'id' => 20,
                'reference_no' => 'tr-20250201-081053',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 630.0,
                'shipping_cost' => NULL,
                'grand_total' => 630.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-01 00:00:00',
                'updated_at' => '2025-02-01 20:10:53',
            ),
            20 => 
            array (
                'id' => 21,
                'reference_no' => 'tr-20250202-031412',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 684.0,
                'shipping_cost' => NULL,
                'grand_total' => 684.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-02 00:00:00',
                'updated_at' => '2025-02-02 15:14:12',
            ),
            21 => 
            array (
                'id' => 22,
                'reference_no' => 'tr-20250202-062752',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1240.0,
                'shipping_cost' => NULL,
                'grand_total' => 1240.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-02 00:00:00',
                'updated_at' => '2025-02-02 18:27:52',
            ),
            22 => 
            array (
                'id' => 23,
                'reference_no' => 'tr-20250206-041010',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 716.0,
                'shipping_cost' => NULL,
                'grand_total' => 716.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-03 00:00:00',
                'updated_at' => '2025-02-06 16:10:10',
            ),
            23 => 
            array (
                'id' => 24,
                'reference_no' => 'tr-20250206-041803',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1150.0,
                'shipping_cost' => NULL,
                'grand_total' => 1150.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-03 00:00:00',
                'updated_at' => '2025-02-06 16:18:03',
            ),
            24 => 
            array (
                'id' => 25,
                'reference_no' => 'tr-20250206-043143',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 680.0,
                'shipping_cost' => NULL,
                'grand_total' => 680.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-04 00:00:00',
                'updated_at' => '2025-02-06 16:31:43',
            ),
            25 => 
            array (
                'id' => 26,
                'reference_no' => 'tr-20250206-043354',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 573.0,
                'shipping_cost' => NULL,
                'grand_total' => 573.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-04 00:00:00',
                'updated_at' => '2025-02-06 16:33:54',
            ),
            26 => 
            array (
                'id' => 28,
                'reference_no' => 'tr-20250206-045512',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1025.0,
                'shipping_cost' => NULL,
                'grand_total' => 1025.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-04 00:00:00',
                'updated_at' => '2025-02-06 16:55:12',
            ),
            27 => 
            array (
                'id' => 29,
                'reference_no' => 'tr-20250206-051434',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 788.0,
                'shipping_cost' => NULL,
                'grand_total' => 788.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-04 00:00:00',
                'updated_at' => '2025-02-06 17:14:34',
            ),
            28 => 
            array (
                'id' => 30,
                'reference_no' => 'tr-20250206-052326',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 730.0,
                'shipping_cost' => NULL,
                'grand_total' => 730.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-05 00:00:00',
                'updated_at' => '2025-02-06 17:23:26',
            ),
            29 => 
            array (
                'id' => 31,
                'reference_no' => 'tr-20250206-053221',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 471.0,
                'shipping_cost' => NULL,
                'grand_total' => 471.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-05 00:00:00',
                'updated_at' => '2025-02-06 17:32:21',
            ),
            30 => 
            array (
                'id' => 32,
                'reference_no' => 'tr-20250206-053551',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 645.0,
                'shipping_cost' => NULL,
                'grand_total' => 645.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-05 00:00:00',
                'updated_at' => '2025-02-06 17:35:51',
            ),
            31 => 
            array (
                'id' => 33,
                'reference_no' => 'tr-20250206-053801',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 2,
                'total_qty' => 2.0,
                'total_tax' => 0.0,
                'total_cost' => 1576.0,
                'shipping_cost' => NULL,
                'grand_total' => 1576.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-05 00:00:00',
                'updated_at' => '2025-02-06 17:38:01',
            ),
            32 => 
            array (
                'id' => 34,
                'reference_no' => 'tr-20250206-054610',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 414.0,
                'shipping_cost' => NULL,
                'grand_total' => 414.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-05 00:00:00',
                'updated_at' => '2025-02-06 17:46:10',
            ),
            33 => 
            array (
                'id' => 35,
                'reference_no' => 'tr-20250206-054757',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 630.0,
                'shipping_cost' => NULL,
                'grand_total' => 630.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-06 00:00:00',
                'updated_at' => '2025-02-06 17:47:57',
            ),
            34 => 
            array (
                'id' => 36,
                'reference_no' => 'tr-20250206-055116',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1600.0,
                'shipping_cost' => NULL,
                'grand_total' => 1600.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-06 00:00:00',
                'updated_at' => '2025-02-06 17:51:16',
            ),
            35 => 
            array (
                'id' => 37,
                'reference_no' => 'tr-20250206-055456',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1119.0,
                'shipping_cost' => NULL,
                'grand_total' => 1119.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-06 00:00:00',
                'updated_at' => '2025-02-06 17:54:56',
            ),
            36 => 
            array (
                'id' => 38,
                'reference_no' => 'tr-20250206-072942',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 788.0,
                'shipping_cost' => NULL,
                'grand_total' => 788.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-06 00:00:00',
                'updated_at' => '2025-02-06 19:29:42',
            ),
            37 => 
            array (
                'id' => 39,
                'reference_no' => 'tr-20250206-075744',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 2380.0,
                'shipping_cost' => NULL,
                'grand_total' => 2380.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-06 00:00:00',
                'updated_at' => '2025-02-06 19:57:44',
            ),
            38 => 
            array (
                'id' => 40,
                'reference_no' => 'tr-20250206-082654',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1250.0,
                'shipping_cost' => NULL,
                'grand_total' => 1250.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-06 00:00:00',
                'updated_at' => '2025-02-06 20:26:54',
            ),
            39 => 
            array (
                'id' => 41,
                'reference_no' => 'tr-20250207-072204',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1600.0,
                'shipping_cost' => NULL,
                'grand_total' => 1600.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-07 00:00:00',
                'updated_at' => '2025-02-07 19:22:04',
            ),
            40 => 
            array (
                'id' => 42,
                'reference_no' => 'tr-20250207-073852',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1120.0,
                'shipping_cost' => NULL,
                'grand_total' => 1120.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-07 00:00:00',
                'updated_at' => '2025-02-07 19:38:52',
            ),
            41 => 
            array (
                'id' => 43,
                'reference_no' => 'tr-20250207-074445',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1300.0,
                'shipping_cost' => NULL,
                'grand_total' => 1300.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-07 00:00:00',
                'updated_at' => '2025-02-07 19:44:45',
            ),
            42 => 
            array (
                'id' => 44,
                'reference_no' => 'tr-20250207-083203',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 645.0,
                'shipping_cost' => NULL,
                'grand_total' => 645.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-07 00:00:00',
                'updated_at' => '2025-02-07 20:32:03',
            ),
            43 => 
            array (
                'id' => 45,
                'reference_no' => 'tr-20250208-024835',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1120.0,
                'shipping_cost' => NULL,
                'grand_total' => 1120.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-08 00:00:00',
                'updated_at' => '2025-02-08 14:48:35',
            ),
            44 => 
            array (
                'id' => 46,
                'reference_no' => 'tr-20250208-051812',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1600.0,
                'shipping_cost' => NULL,
                'grand_total' => 1600.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-08 00:00:00',
                'updated_at' => '2025-02-08 17:18:12',
            ),
            45 => 
            array (
                'id' => 47,
                'reference_no' => 'tr-20250208-075624',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1119.0,
                'shipping_cost' => NULL,
                'grand_total' => 1119.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-08 00:00:00',
                'updated_at' => '2025-02-08 19:56:24',
            ),
            46 => 
            array (
                'id' => 48,
                'reference_no' => 'tr-20250209-120359',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 645.0,
                'shipping_cost' => NULL,
                'grand_total' => 645.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-09 00:00:00',
                'updated_at' => '2025-02-09 12:03:59',
            ),
            47 => 
            array (
                'id' => 49,
                'reference_no' => 'tr-20250209-055847',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1700.0,
                'shipping_cost' => NULL,
                'grand_total' => 1700.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-09 00:00:00',
                'updated_at' => '2025-02-09 17:58:47',
            ),
            48 => 
            array (
                'id' => 50,
                'reference_no' => 'tr-20250209-073322',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1240.0,
                'shipping_cost' => NULL,
                'grand_total' => 1240.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-09 00:00:00',
                'updated_at' => '2025-02-09 19:33:22',
            ),
            49 => 
            array (
                'id' => 51,
                'reference_no' => 'tr-20250209-090926',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 102,
                'total_qty' => 122.0,
                'total_tax' => 0.0,
                'total_cost' => 141310.0,
                'shipping_cost' => NULL,
                'grand_total' => 141310.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-09 00:00:00',
                'updated_at' => '2025-02-09 21:09:26',
            ),
            50 => 
            array (
                'id' => 52,
                'reference_no' => 'tr-20250210-053800',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 6,
                'total_qty' => 6.0,
                'total_tax' => 0.0,
                'total_cost' => 3216.0,
                'shipping_cost' => NULL,
                'grand_total' => 3216.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-10 00:00:00',
                'updated_at' => '2025-02-10 17:38:00',
            ),
            51 => 
            array (
                'id' => 53,
                'reference_no' => 'tr-20250210-081418',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 472.0,
                'shipping_cost' => NULL,
                'grand_total' => 472.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-10 00:00:00',
                'updated_at' => '2025-02-10 20:14:18',
            ),
            52 => 
            array (
                'id' => 54,
                'reference_no' => 'tr-20250211-114133',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 500.0,
                'shipping_cost' => NULL,
                'grand_total' => 500.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-11 00:00:00',
                'updated_at' => '2025-02-11 11:41:33',
            ),
            53 => 
            array (
                'id' => 55,
                'reference_no' => 'tr-20250211-035358',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 471.0,
                'shipping_cost' => NULL,
                'grand_total' => 471.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-11 00:00:00',
                'updated_at' => '2025-02-11 15:53:58',
            ),
            54 => 
            array (
                'id' => 56,
                'reference_no' => 'tr-20250211-070804',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 972.0,
                'shipping_cost' => NULL,
                'grand_total' => 972.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-11 00:00:00',
                'updated_at' => '2025-02-11 19:08:04',
            ),
            55 => 
            array (
                'id' => 57,
                'reference_no' => 'tr-20250211-075308',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 972.0,
                'shipping_cost' => NULL,
                'grand_total' => 972.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-11 00:00:00',
                'updated_at' => '2025-02-11 19:53:08',
            ),
            56 => 
            array (
                'id' => 58,
                'reference_no' => 'tr-20250211-084854',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 684.0,
                'shipping_cost' => NULL,
                'grand_total' => 684.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-02-11 00:00:00',
                'updated_at' => '2025-02-11 20:48:54',
            ),
        ));
        
        
    }
}