<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TransfersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('transfers')->delete();
        
        \DB::table('transfers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'reference_no' => 'tr-20250127-062944',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 580.0,
                'shipping_cost' => NULL,
                'grand_total' => 580.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:29:44',
            ),
            1 => 
            array (
                'id' => 2,
                'reference_no' => 'tr-20250127-063302',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1150.0,
                'shipping_cost' => NULL,
                'grand_total' => 1150.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:33:02',
            ),
            2 => 
            array (
                'id' => 3,
                'reference_no' => 'tr-20250127-063513',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 2380.0,
                'shipping_cost' => NULL,
                'grand_total' => 2380.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:35:13',
            ),
            3 => 
            array (
                'id' => 4,
                'reference_no' => 'tr-20250127-064415',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 580.0,
                'shipping_cost' => NULL,
                'grand_total' => 580.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:44:15',
            ),
            4 => 
            array (
                'id' => 5,
                'reference_no' => 'tr-20250127-064545',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 730.0,
                'shipping_cost' => NULL,
                'grand_total' => 730.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 00:00:00',
                'updated_at' => '2025-01-27 18:45:45',
            ),
            5 => 
            array (
                'id' => 6,
                'reference_no' => 'tr-20250127-065155',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 4,
                'total_qty' => 4.0,
                'total_tax' => 0.0,
                'total_cost' => 5800.0,
                'shipping_cost' => NULL,
                'grand_total' => 5800.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-27 18:51:55',
                'updated_at' => '2025-01-27 18:51:55',
            ),
            6 => 
            array (
                'id' => 7,
                'reference_no' => 'tr-20250128-045115',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1600.0,
                'shipping_cost' => NULL,
                'grand_total' => 1600.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 16:51:15',
                'updated_at' => '2025-01-28 16:51:15',
            ),
            7 => 
            array (
                'id' => 8,
                'reference_no' => 'tr-20250128-045459',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1600.0,
                'shipping_cost' => NULL,
                'grand_total' => 1600.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 16:54:59',
                'updated_at' => '2025-01-28 16:54:59',
            ),
            8 => 
            array (
                'id' => 9,
                'reference_no' => 'tr-20250128-065332',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 760.0,
                'shipping_cost' => NULL,
                'grand_total' => 760.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 00:00:00',
                'updated_at' => '2025-01-28 18:53:32',
            ),
            9 => 
            array (
                'id' => 10,
                'reference_no' => 'tr-20250128-065755',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 5,
                'total_qty' => 5.0,
                'total_tax' => 0.0,
                'total_cost' => 3800.0,
                'shipping_cost' => NULL,
                'grand_total' => 3800.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 18:57:55',
                'updated_at' => '2025-01-28 18:57:55',
            ),
            10 => 
            array (
                'id' => 11,
                'reference_no' => 'tr-20250128-070019',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1175.0,
                'shipping_cost' => NULL,
                'grand_total' => 1175.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 00:00:00',
                'updated_at' => '2025-01-28 19:00:19',
            ),
            11 => 
            array (
                'id' => 12,
                'reference_no' => 'tr-20250128-072840',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 594.0,
                'shipping_cost' => NULL,
                'grand_total' => 594.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-28 19:28:40',
                'updated_at' => '2025-01-28 19:28:40',
            ),
            12 => 
            array (
                'id' => 13,
                'reference_no' => 'tr-20250130-022310',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 645.0,
                'shipping_cost' => NULL,
                'grand_total' => 645.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-30 00:00:00',
                'updated_at' => '2025-01-30 14:23:10',
            ),
            13 => 
            array (
                'id' => 14,
                'reference_no' => 'tr-20250130-054153',
                'user_id' => 1,
                'status' => 1,
                'from_warehouse_id' => 4,
                'to_warehouse_id' => 1,
                'item' => 1,
                'total_qty' => 1.0,
                'total_tax' => 0.0,
                'total_cost' => 1120.0,
                'shipping_cost' => NULL,
                'grand_total' => 1120.0,
                'document' => NULL,
                'note' => NULL,
                'created_at' => '2025-01-30 00:00:00',
                'updated_at' => '2025-01-30 17:41:53',
            ),
        ));
        
        
    }
}